import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:drift/drift.dart';
import 'package:go_router/go_router.dart';

import '../../core/providers/alert_provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/models/alert_tab.dart';
import '../../core/models/space_type.dart';
import '../../core/providers/database_provider.dart';
import '../../core/providers/space_skin_provider.dart';
import '../../core/utils/alert_display_helper.dart';
import '../../data/database/app_database.dart';
import '../common/widgets/async_list_body.dart';
import '../common/widgets/guanguan_celebration_snackbar.dart';
import '../common/widgets/warm_scaffold.dart';
import '../items/widgets/usage_dialog.dart';
import 'widgets/alert_card.dart';

export '../../core/models/alert_tab.dart';

/// 提醒中心 — 工具风 Tab + 批量已读
class AlertCenterPage extends ConsumerStatefulWidget {
  const AlertCenterPage({super.key, this.initialTab});

  /// 路由 `?tab=expiry|stock|restock|warranty` 指定初始 Tab
  final AlertTab? initialTab;

  @override
  ConsumerState<AlertCenterPage> createState() => _AlertCenterPageState();
}

class _AlertCenterPageState extends ConsumerState<AlertCenterPage>
    with SingleTickerProviderStateMixin {
  TabController? _tabController;
  bool _tabInitialized = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_tabInitialized) return;
    _tabInitialized = true;

    // B4：店铺空间无路由 tab 时默认打开低库存 Tab
    final tab = widget.initialTab ??
        (ref.read(spaceSkinProvider).spaceType == SpaceType.shop
            ? AlertTab.stock
            : AlertTab.all);
    final index =
        AlertTab.values.indexOf(tab).clamp(0, AlertTab.values.length - 1);
    _tabController = TabController(
      length: AlertTab.values.length,
      vsync: this,
      initialIndex: index,
    );
    debugPrint('[AlertCenter] INFO: 初始 Tab=$tab spaceType=${ref.read(spaceSkinProvider).spaceType.apiValue}');
  }

  @override
  void dispose() {
    _tabController?.dispose();
    super.dispose();
  }

  void _markAsUsed(Item item) async {
    final skin = ref.read(spaceSkinProvider);
    debugPrint('[AlertCenter] INFO: 今天用掉 itemId=${item.id}');
    final ok = await recordQuickUsage(ref: ref, item: item);
    if (mounted && ok) {
      final remaining =
          (item.currentQuantity - 1).clamp(0.0, double.infinity);
      GuanguanCelebrationSnackBar.show(
        context,
        message: skin.celebrateConsume(
          itemName: item.name,
          depleted: remaining <= 0,
        ),
      );
    }
  }

  void _markAsDiscarded(Item item) async {
    final skin = ref.read(spaceSkinProvider);
    debugPrint('[AlertCenter] INFO: 已丢弃 itemId=${item.id}');
    await recordItemDiscard(ref: ref, item: item);
    if (mounted) {
      GuanguanCelebrationSnackBar.show(
        context,
        message: skin.celebrateDiscard(item.name),
      );
    }
  }

  void _addToShoppingList(Item item) async {
    final skin = ref.read(spaceSkinProvider);
    final db = ref.read(databaseProvider);

    await db.insertShoppingListItem(ShoppingListCompanion.insert(
      name: item.name,
      relatedItemId: Value(item.id),
      quantity: Value(item.purchaseQuantity.toDouble()),
      unit: Value(item.unit),
      estimatedPrice:
          item.purchasePrice != null ? Value(item.purchasePrice!) : const Value.absent(),
      isAutoGenerated: const Value(true),
    ));

    if (mounted) {
      GuanguanCelebrationSnackBar.show(
        context,
        message: skin.celebrateAddShopping(item.name),
      );
    }
  }

  Future<void> _markAllAsRead() async {
    debugPrint('[AlertCenter] INFO: 全部已读');
    await markAllAlertsReadAction(ref);
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('已标记所有提醒为已读')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final tabController = _tabController;
    if (tabController == null) {
      return const WarmScaffold(
        title: '提醒中心',
        body: Center(child: CircularProgressIndicator()),
      );
    }

    return WarmScaffold(
      title: '提醒中心',
      actions: [
        TextButton(
          onPressed: _markAllAsRead,
          child: const Text('全部已读'),
        ),
      ],
      bottom: TabBar(
        controller: tabController,
        isScrollable: true,
        labelColor: AppColors.primaryDark,
        unselectedLabelColor: AppColors.textSecondary,
        indicatorColor: AppColors.primary,
        tabs: AlertTab.values
            .map((t) => Tab(text: alertTabLabels[t]))
            .toList(),
      ),
      body: TabBarView(
        controller: tabController,
        children: [
          for (final tab in AlertTab.values) _buildAlertList(tab),
        ],
      ),
    );
  }

  Widget _buildAlertList(AlertTab tab) {
    final alertsAsync = ref.watch(alertListProvider(tab));

    return RefreshIndicator(
      onRefresh: () async => invalidateAlertProviders(ref),
      child: alertsAsync.when(
        loading: () => const AsyncListBody(
          isLoading: true,
          isEmpty: false,
          emptyIcon: Icons.notifications_outlined,
          emptyTitle: '',
          child: SizedBox.shrink(),
        ),
        error: (error, _) => ListView(
          physics: const AlwaysScrollableScrollPhysics(),
          children: [
            AsyncListBody(
              isLoading: false,
              isEmpty: false,
              errorMessage: '$error',
              onRetry: () => invalidateAlertProviders(ref),
              emptyIcon: Icons.error_outline,
              emptyTitle: '',
              child: const SizedBox.shrink(),
            ),
          ],
        ),
        data: (alerts) {
          if (alerts.isEmpty) {
            return ListView(
              physics: const AlwaysScrollableScrollPhysics(),
              children: const [
                AsyncListBody(
                  isLoading: false,
                  isEmpty: true,
                  emptyIcon: Icons.check_circle_outline,
                  emptyTitle: '一切安好',
                  emptySubtitle: '没有待处理的提醒',
                  child: SizedBox.shrink(),
                ),
              ],
            );
          }

          return ListView.builder(
            physics: const AlwaysScrollableScrollPhysics(),
            padding: const EdgeInsets.all(16),
            itemCount: alerts.length,
            itemBuilder: (context, index) {
              final (item, type) = alerts[index];
              final alertKey = alertTypeToKey(type);
              final detailUri = type == AlertType.expiry
                  ? '/items/${item.id}?action=consume&alert=$alertKey'
                  : '/items/${item.id}?alert=$alertKey';
              return Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: AlertCard(
                  item: item,
                  type: type,
                  onTap: () {
                    debugPrint('[AlertCenter] INFO: 打开详情 itemId=${item.id}');
                    context.push(detailUri);
                  },
                  onUse: type == AlertType.expiry ? () => _markAsUsed(item) : null,
                  onDiscard:
                      type == AlertType.expiry ? () => _markAsDiscarded(item) : null,
                  onAddToShopping: (type == AlertType.stock || type == AlertType.restock)
                      ? () => _addToShoppingList(item)
                      : null,
                  onAcknowledge: type == AlertType.warranty
                      ? () => ignoreAlertAction(ref, item.id, type)
                      : null,
                  onIgnore: type == AlertType.expiry
                      ? () => ignoreAlertAction(ref, item.id, type)
                      : null,
                ),
              );
            },
          );
        },
      ),
    );
  }
}
