import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:drift/drift.dart';
import '../../core/events/item_event_bus.dart';
import '../../core/models/alert_tab.dart';
import '../../core/providers/alert_provider.dart';
import '../../core/providers/database_provider.dart';
import '../../data/database/app_database.dart';
import '../../core/constants/app_colors.dart';
import '../../core/theme/app_visual_style.dart';
import '../../core/theme/cartoon_copy.dart';
import '../common/widgets/app_empty_state.dart';
import '../common/widgets/cartoon_list_entrance.dart';
import '../common/widgets/cartoon_scaffold.dart';
import '../common/widgets/cartoon_tab_bar.dart';
import 'widgets/alert_card.dart';

export '../../core/models/alert_tab.dart';

class AlertCenterPage extends ConsumerStatefulWidget {
  const AlertCenterPage({super.key});

  @override
  ConsumerState<AlertCenterPage> createState() => _AlertCenterPageState();
}

class _AlertCenterPageState extends ConsumerState<AlertCenterPage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 5, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _markAsUsed(Item item) async {
    final db = ref.read(databaseProvider);
    final newQuantity = item.currentQuantity - 1;

    await db.updateItem(item.copyWith(
      currentQuantity: newQuantity,
      status: newQuantity <= 0 ? 1 : item.status,
      updatedAt: DateTime.now(),
    ));

    await db.insertUsageRecord(UsageRecordsCompanion.insert(
      itemId: item.id,
      type: 1,
      quantity: 1,
      remainingQuantity: newQuantity,
    ));

    ref.read(itemEventBusProvider.notifier).notifyUpdated(itemId: item.id);
    invalidateAlertProviders(ref);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('已记录使用1件${item.name}')),
      );
    }
  }

  void _markAsDiscarded(Item item) async {
    final db = ref.read(databaseProvider);

    await db.updateItem(item.copyWith(
      status: 3,
      updatedAt: DateTime.now(),
    ));

    await db.insertUsageRecord(UsageRecordsCompanion.insert(
      itemId: item.id,
      type: 2,
      quantity: item.currentQuantity,
      remainingQuantity: 0,
    ));

    ref.read(itemEventBusProvider.notifier).notifyUpdated(itemId: item.id);
    invalidateAlertProviders(ref);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('${item.name}已标记为丢弃')),
      );
    }
  }

  void _addToShoppingList(Item item) async {
    final db = ref.read(databaseProvider);

    await db.insertShoppingListItem(ShoppingListCompanion.insert(
      name: item.name,
      relatedItemId: Value(item.id),
      quantity: Value(item.purchaseQuantity.toDouble()),
      unit: Value(item.unit),
      estimatedPrice:
          item.purchasePrice != null ? Value(item.purchasePrice!) : const Value.absent(),
      isAutoGenerated: const Value(true),
    ));

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('${item.name}已加入购物清单')),
      );
    }
  }

  Future<void> _markAllAsRead() async {
    await markAllAlertsReadAction(ref);
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('已标记所有提醒为已读')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final cartoonTabs = AlertTab.values
        .map(
          (t) => CartoonTabItem(
            label: alertTabLabels[t]!,
            emoji: alertTabEmojis[t],
          ),
        )
        .toList();

    return CartoonScaffold(
      title: '提醒中心',
      titleEmoji: '🔔',
      actions: [
        Padding(
          padding: const EdgeInsets.only(right: 8),
          child: TextButton(
            onPressed: _markAllAsRead,
            child: const Text('✓ 全部已读'),
          ),
        ),
      ],
      bottom: CartoonTabBar(controller: _tabController, tabs: cartoonTabs),
      body: TabBarView(
        controller: _tabController,
        children: [
          for (final tab in AlertTab.values) _buildAlertList(tab),
        ],
      ),
    );
  }

  Widget _buildAlertList(AlertTab tab) {
    final alertsAsync = ref.watch(alertListProvider(tab));

    return alertsAsync.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Center(child: Text('加载失败: $error')),
      data: (alerts) {
        if (alerts.isEmpty) {
          return const AppEmptyState(
            icon: '😊',
            title: '一切安好',
            subtitle: '没有待处理的提醒',
            cartoonKind: CartoonEmptyKind.alerts,
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: alerts.length,
          itemBuilder: (context, index) {
            final (item, type) = alerts[index];
            return Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: CartoonListEntrance(
                index: index,
                child: AlertCard(
                  item: item,
                  type: type,
                  onUse: type == AlertType.expiry ? () => _markAsUsed(item) : null,
                  onDiscard:
                      type == AlertType.expiry ? () => _markAsDiscarded(item) : null,
                  onAddToShopping: (type == AlertType.stock || type == AlertType.restock)
                      ? () => _addToShoppingList(item)
                      : null,
                  onAcknowledge: type == AlertType.warranty
                      ? () => ignoreAlertAction(ref, item.id, type)
                      : null,
                  onIgnore: type == AlertType.expiry
                      ? () => ignoreAlertAction(ref, item.id, type)
                      : null,
                ),
              ),
            );
          },
        );
      },
    );
  }
}
