import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_radius.dart';

class ShoppingItemCard extends StatelessWidget {
  final String name;
  final double quantity;
  final String unit;
  final double? estimatedPrice;
  final bool isAutoGenerated;
  final bool isChecked;
  final String? reason;
  final VoidCallback? onTap;
  final VoidCallback? onCheckChanged;
  final VoidCallback? onDelete;

  const ShoppingItemCard({
    super.key,
    required this.name,
    required this.quantity,
    required this.unit,
    this.estimatedPrice,
    this.isAutoGenerated = false,
    this.isChecked = false,
    this.reason,
    this.onTap,
    this.onCheckChanged,
    this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: isChecked ? AppColors.successLight.withOpacity(0.3) : AppColors.card,
          borderRadius: BorderRadius.circular(AppRadius.lg),
          border: Border.all(
            color: isChecked ? AppColors.success : AppColors.border,
            width: isChecked ? 2 : 1,
          ),
        ),
        child: Row(
          children: [
            // Checkbox
            GestureDetector(
              onTap: onCheckChanged,
              child: Container(
                width: 24,
                height: 24,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  border: Border.all(
                    color: isChecked ? AppColors.success : AppColors.textHint,
                    width: 2,
                  ),
                  color: isChecked ? AppColors.success : Colors.transparent,
                ),
                child: isChecked
                    ? const Icon(Icons.check, size: 16, color: Colors.white)
                    : null,
              ),
            ),
            const SizedBox(width: 12),

            // Content
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          name,
                          style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                                fontWeight: FontWeight.w500,
                                decoration: isChecked
                                    ? TextDecoration.lineThrough
                                    : null,
                                color: isChecked
                                    ? AppColors.textHint
                                    : AppColors.textPrimary,
                              ),
                        ),
                      ),
                      if (isAutoGenerated)
                        Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 8,
                            vertical: 2,
                          ),
                          decoration: BoxDecoration(
                            color: AppColors.primary.withOpacity(0.1),
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: Text(
                            '推荐',
                            style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                  color: AppColors.primary,
                                  fontWeight: FontWeight.w500,
                                ),
                          ),
                        ),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      Text(
                        '${quantity.toStringAsFixed(quantity == quantity.toInt() ? 0 : 1)} $unit',
                        style: Theme.of(context).textTheme.bodySmall?.copyWith(
                              color: AppColors.textSecondary,
                            ),
                      ),
                      if (estimatedPrice != null) ...[
                        const SizedBox(width: 8),
                        Text(
                          '¥${estimatedPrice!.toStringAsFixed(2)}',
                          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: AppColors.textHint,
                              ),
                        ),
                      ],
                      if (reason != null) ...[
                        const SizedBox(width: 8),
                        Text(
                          reason!,
                          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: AppColors.warning,
                              ),
                        ),
                      ],
                    ],
                  ),
                ],
              ),
            ),

            // Delete button
            if (onDelete != null)
              IconButton(
                onPressed: onDelete,
                icon: const Icon(Icons.delete_outline, color: AppColors.textHint),
              ),
          ],
        ),
      ),
    );
  }
}
