import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_radius.dart';
import '../../../core/theme/app_decorations.dart';
import '../../../core/theme/cartoon_palette.dart';
import '../../common/widgets/cartoon_pressable.dart';
import '../../common/widgets/cartoon_ui.dart';
import '../../common/widgets/tag_chip.dart';

/// 购物清单条目 — 工具风白卡 / 卡通贴纸双分支
class ShoppingItemCard extends StatelessWidget {
  final String name;
  final double quantity;
  final String unit;
  final double? estimatedPrice;
  final bool isAutoGenerated;
  final bool isChecked;
  final String? reason;
  final VoidCallback? onTap;
  final VoidCallback? onCheckChanged;
  final VoidCallback? onDelete;
  final int cartoonIndex;

  const ShoppingItemCard({
    super.key,
    required this.name,
    required this.quantity,
    required this.unit,
    this.estimatedPrice,
    this.isAutoGenerated = false,
    this.isChecked = false,
    this.reason,
    this.onTap,
    this.onCheckChanged,
    this.onDelete,
    this.cartoonIndex = 0,
  });

  String _quantityLabel() {
    final qtyText = quantity.toStringAsFixed(
      quantity == quantity.roundToDouble() ? 0 : 1,
    );
    if (estimatedPrice == null) {
      return '$qtyText $unit';
    }
    return '$qtyText $unit · 约¥${estimatedPrice!.toStringAsFixed(2)}';
  }

  @override
  Widget build(BuildContext context) {
    if (AppColors.isUtilityStyle) {
      return _buildUtilityCard(context);
    }
    return _buildCartoonCard(context);
  }

  /// 工具风 — 白底列表行 + TagChip
  Widget _buildUtilityCard(BuildContext context) {
    return Material(
      color: AppColors.white,
      borderRadius: BorderRadius.circular(AppRadius.md),
      elevation: 1,
      shadowColor: Colors.black.withValues(alpha: 0.06),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(AppRadius.md),
        child: Padding(
          padding: const EdgeInsets.all(14),
          child: Row(
            children: [
              _buildCheckbox(isUtility: true),
              const SizedBox(width: 12),
              Expanded(child: _buildContent(context, isUtility: true)),
              if (onDelete != null)
                IconButton(
                  icon: const Icon(Icons.delete_outline,
                      color: AppColors.danger, size: 22),
                  onPressed: onDelete,
                ),
            ],
          ),
        ),
      ),
    );
  }

  /// 卡通风 — 贴纸色块
  Widget _buildCartoonCard(BuildContext context) {
    final (fill, border) = CartoonPalette.pairAt(cartoonIndex);

    return CartoonPressable(
      onTap: onTap,
      child: AppSurface(
        fillColor: isChecked ? CartoonPalette.pastelMint : fill,
        borderColor: isChecked ? AppColors.success : border,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              _buildCheckbox(isUtility: false),
              const SizedBox(width: 12),
              Expanded(child: _buildContent(context, isUtility: false, border: border, fill: fill)),
              if (onDelete != null)
                IconButton(
                  icon: const Icon(Icons.delete_outline,
                      color: AppColors.danger, size: 22),
                  onPressed: onDelete,
                ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildCheckbox({required bool isUtility}) {
    return GestureDetector(
      onTap: onCheckChanged,
      child: Container(
        width: isUtility ? 22 : 28,
        height: isUtility ? 22 : 28,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          border: Border.all(
            color: isChecked
                ? AppColors.success
                : (isUtility ? AppColors.border : AppColors.primaryDark),
            width: isUtility ? 1.5 : 2.5,
          ),
          color: isChecked ? AppColors.success : Colors.transparent,
        ),
        child: isChecked
            ? Icon(Icons.check, size: isUtility ? 14 : 16, color: Colors.white)
            : null,
      ),
    );
  }

  Widget _buildContent(
    BuildContext context, {
    required bool isUtility,
    Color? border,
    Color? fill,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(
              child: Text(
                name,
                style: Theme.of(context).textTheme.titleSmall?.copyWith(
                      fontWeight: FontWeight.w700,
                      decoration:
                          isChecked ? TextDecoration.lineThrough : null,
                      color: isChecked
                          ? AppColors.textHint
                          : AppColors.textPrimary,
                    ),
              ),
            ),
            if (isAutoGenerated)
              isUtility
                  ? TagChip(
                      label: '自动推荐',
                      color: AppColors.primary,
                      background: AppColors.primary.withValues(alpha: 0.1),
                    )
                  : CartoonStickerBadge(
                      label: '自动推荐',
                      accentColor: AppColors.primaryDark,
                      fillColor: AppColors.primaryLighter,
                      fontSize: 10,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 6,
                        vertical: 2,
                      ),
                    ),
          ],
        ),
        const SizedBox(height: 6),
        isUtility
            ? TagChip(
                label: _quantityLabel(),
                color: isChecked ? AppColors.success : AppColors.textSecondary,
                background: isChecked
                    ? AppColors.successLight
                    : AppColors.gray100,
              )
            : CartoonStickerBadge(
                label: _quantityLabel(),
                accentColor: isChecked ? AppColors.success : border!,
                fillColor: isChecked
                    ? AppColors.successLight
                    : fill!.withValues(alpha: 0.6),
                fontSize: 11,
              ),
        if (reason != null) ...[
          const SizedBox(height: 6),
          Text(
            reason!,
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  color: AppColors.textHint,
                  fontWeight: FontWeight.w500,
                  fontSize: 11,
                ),
          ),
        ],
      ],
    );
  }
}
