import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/theme/app_decorations.dart';
import '../../../core/theme/cartoon_palette.dart';
import '../../common/widgets/cartoon_pressable.dart';
import '../../common/widgets/cartoon_ui.dart';

/// Shopping list item card with cartoon sticker styling.
class ShoppingItemCard extends StatelessWidget {
  final String name;
  final double quantity;
  final String unit;
  final double? estimatedPrice;
  final bool isAutoGenerated;
  final bool isChecked;
  final String? reason;
  final VoidCallback? onTap;
  final VoidCallback? onCheckChanged;
  final VoidCallback? onDelete;
  final int cartoonIndex;

  const ShoppingItemCard({
    super.key,
    required this.name,
    required this.quantity,
    required this.unit,
    this.estimatedPrice,
    this.isAutoGenerated = false,
    this.isChecked = false,
    this.reason,
    this.onTap,
    this.onCheckChanged,
    this.onDelete,
    this.cartoonIndex = 0,
  });

  String _quantityLabel() {
    final qtyText = quantity.toStringAsFixed(
      quantity == quantity.roundToDouble() ? 0 : 1,
    );
    if (estimatedPrice == null) {
      return '$qtyText $unit';
    }
    return '$qtyText $unit ? ?${estimatedPrice!.toStringAsFixed(2)}';
  }

  @override
  Widget build(BuildContext context) {
    final (fill, border) = CartoonPalette.pairAt(cartoonIndex);

    final body = Padding(
      padding: const EdgeInsets.all(16),
      child: Row(
        children: [
          GestureDetector(
            onTap: onCheckChanged,
            child: Container(
              width: 28,
              height: 28,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(
                  color: isChecked ? AppColors.success : AppColors.primaryDark,
                  width: 2.5,
                ),
                color: isChecked ? AppColors.success : Colors.transparent,
              ),
              child: isChecked
                  ? const Icon(Icons.check, size: 16, color: Colors.white)
                  : null,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        name,
                        style: Theme.of(context).textTheme.titleSmall?.copyWith(
                              fontWeight: FontWeight.w800,
                              decoration: isChecked
                                  ? TextDecoration.lineThrough
                                  : null,
                              color: isChecked
                                  ? AppColors.textHint
                                  : AppColors.textPrimary,
                            ),
                      ),
                    ),
                    if (isAutoGenerated)
                      CartoonStickerBadge(
                        label: '?? ??',
                        accentColor: AppColors.primaryDark,
                        fillColor: AppColors.primaryLighter,
                        fontSize: 10,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 6,
                          vertical: 2,
                        ),
                      ),
                  ],
                ),
                const SizedBox(height: 6),
                CartoonStickerBadge(
                  label: _quantityLabel(),
                  accentColor: isChecked ? AppColors.success : border,
                  fillColor: isChecked
                      ? AppColors.successLight
                      : fill.withValues(alpha: 0.6),
                  fontSize: 11,
                ),
                if (reason != null) ...[
                  const SizedBox(height: 6),
                  Text(
                    reason!,
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: AppColors.textHint,
                          fontWeight: FontWeight.w600,
                          fontSize: 11,
                        ),
                  ),
                ],
              ],
            ),
          ),
          if (onDelete != null)
            IconButton(
              icon: const Icon(Icons.delete_outline,
                  color: AppColors.danger, size: 22),
              onPressed: onDelete,
            ),
        ],
      ),
    );

    return CartoonPressable(
      onTap: onTap,
      child: AppSurface(
        fillColor: isChecked ? CartoonPalette.pastelMint : fill,
        borderColor: isChecked ? AppColors.success : border,
        child: body,
      ),
    );
  }
}
