import 'dart:io';
import 'package:flutter/foundation.dart' show debugPrint;
import 'package:drift/drift.dart';
import 'package:drift_sqflite/drift_sqflite.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as path;
import '../../core/config/space_shop_seed_data.dart';
import '../../core/utils/alert_display_helper.dart';
part 'app_database.g.dart';

// 分类表
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get icon => text()();
  TextColumn get color => text()();
  IntColumn get parentId => integer().nullable()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  BoolColumn get isSystem => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 位置表
class Locations extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get icon => text().nullable()();
  TextColumn get images => text().nullable()();
  IntColumn get parentId => integer().nullable()();
  IntColumn get level => integer().withDefault(const Constant(1))();
  TextColumn get fullPath => text()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 物品表
class Items extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get brand => text().nullable()();
  TextColumn get specification => text().nullable()();
  TextColumn get barcode => text().nullable()();
  IntColumn get categoryId => integer()();
  IntColumn get locationId => integer().nullable()();
  TextColumn get containerName => text().nullable()();
  RealColumn get purchasePrice => real().nullable()();
  /// B+ 售价 — 店铺场景零售价
  RealColumn get salePrice => real().nullable()();
  /// B+ 供应商 — 店铺场景
  TextColumn get supplier => text().nullable()();
  IntColumn get purchaseQuantity => integer().withDefault(const Constant(1))();
  TextColumn get packageUnit => text().nullable()();
  IntColumn get packageQuantity => integer().withDefault(const Constant(1))();
  RealColumn get currentQuantity => real().withDefault(const Constant(1))();
  TextColumn get unit => text().withDefault(const Constant('件'))();
  RealColumn get safetyStock => real().withDefault(const Constant(1))();
  DateTimeColumn get purchaseDate => dateTime().nullable()();
  TextColumn get purchaseChannel => text().nullable()();
  DateTimeColumn get productionDate => dateTime().nullable()();
  DateTimeColumn get expiryDate => dateTime().nullable()();
  IntColumn get shelfLifeDays => integer().nullable()();
  DateTimeColumn get openedDate => dateTime().nullable()();
  IntColumn get afterOpenDays => integer().nullable()();
  DateTimeColumn get warrantyDate => dateTime().nullable()();
  IntColumn get expiryAlertDays => integer().withDefault(const Constant(3))();
  BoolColumn get stockAlert => boolean().withDefault(const Constant(true))();
  TextColumn get images => text().nullable()();
  TextColumn get notes => text().nullable()();
  IntColumn get status => integer().withDefault(const Constant(0))();
  RealColumn get avgDailyConsumption => real().nullable()();
  DateTimeColumn get predictedEmptyDate => dateTime().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
  /// 服务端 items.id — 本地主键与服务端不一致时用于 API / usage 映射
  IntColumn get serverItemId => integer().nullable()();
}

// 使用记录表
class UsageRecords extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get itemId => integer()();
  IntColumn get type => integer()(); // 0入库/1使用/2丢弃/3移动/4调整
  RealColumn get quantity => real()();
  RealColumn get remainingQuantity => real()();
  TextColumn get operatorName => text().nullable()();
  /// 服务端 usage_records.id — 用于多端去重与补推
  IntColumn get serverRecordId => integer().nullable()();
  TextColumn get notes => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 购物清单表
class ShoppingList extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  IntColumn get relatedItemId => integer().nullable()();
  RealColumn get quantity => real().withDefault(const Constant(1))();
  TextColumn get unit => text().withDefault(const Constant('件'))();
  RealColumn get estimatedPrice => real().nullable()();
  BoolColumn get isPurchased => boolean().withDefault(const Constant(false))();
  BoolColumn get isAutoGenerated => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 家庭成员表
class FamilyMembers extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get avatar => text().nullable()();
  TextColumn get role => text().withDefault(const Constant('member'))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// 提醒已读/忽略状态（通知中心 Epic E1）
@TableIndex(name: 'alert_read_unique', columns: {#itemId, #alertType, #familyId}, unique: true)
class AlertReadStates extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get itemId => integer()();
  TextColumn get alertType => text()();
  IntColumn get familyId => integer().withDefault(const Constant(0))();
  DateTimeColumn get readAt => dateTime().nullable()();
  BoolColumn get ignored => boolean().withDefault(const Constant(false))();
}

/// 问管管对话记录 — 本地持久化（方案 A）
class AssistantMessages extends Table {
  IntColumn get id => integer().autoIncrement()();
  BoolColumn get isUser => boolean()();
  TextColumn get content => text()();
  /// JSON：items / actionLabel / actionRoute
  TextColumn get metaJson => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

@DriftDatabase(
  tables: [
    Categories,
    Locations,
    Items,
    UsageRecords,
    ShoppingList,
    FamilyMembers,
    AlertReadStates,
    AssistantMessages,
  ],
)
class AppDatabase extends _$AppDatabase {
  static final AppDatabase _instance = AppDatabase._internal();

  factory AppDatabase() => _instance;

  AppDatabase._internal() : super(_openConnection());
  
  @override
  int get schemaVersion => 7;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          await m.createTable(alertReadStates);
        }
        if (from < 3) {
          await m.addColumn(usageRecords, usageRecords.serverRecordId);
        }
        if (from < 4) {
          await m.addColumn(items, items.serverItemId);
        }
        if (from < 5) {
          await m.addColumn(items, items.salePrice);
        }
        if (from < 6) {
          await m.addColumn(items, items.supplier);
        }
        if (from < 7) {
          await m.createTable(assistantMessages);
        }
      },
    );
  }
  
  Future<void>? _seedDataFuture;
  
  Future<void> ensureInitialized() {
    if (_seedDataFuture == null) {
      _seedDataFuture = seedData();
    }
    return _seedDataFuture!;
  }
  
  static LazyDatabase _openConnection() {
    return LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(path.join(dbFolder.path, 'homestock.db'));
      try {
        return SqfliteQueryExecutor.inDatabaseFolder(path: 'homestock.db');
      } catch (e) {
        // 数据库 schema 不匹配（旧版本升级）→ 删除重建
        debugPrint('[DB] WARN: 数据库打开失败，可能是旧版本 schema 不匹配，删除重建 - $e');
        if (await file.exists()) {
          await file.delete();
        }
        return SqfliteQueryExecutor.inDatabaseFolder(path: 'homestock.db');
      }
    });
  }

  // ==================== Categories DAO ====================
  
  // 获取所有顶级分类
  Future<List<Category>> getTopLevelCategories() {
    return (select(categories)
          ..where((c) => c.parentId.isNull())
          ..orderBy([(c) => OrderingTerm(expression: c.sortOrder)]))
        .get();
  }

  // 获取指定父级的子分类
  Future<List<Category>> getChildCategories(int parentId) {
    return (select(categories)
          ..where((c) => c.parentId.equals(parentId))
          ..orderBy([(c) => OrderingTerm(expression: c.sortOrder)]))
        .get();
  }

  // 插入自定义分类
  Future<int> insertCategory(CategoriesCompanion category) {
    return into(categories).insert(category);
  }

  // 根据 ID 获取分类
  Future<Category?> getCategoryById(int id) {
    return (select(categories)..where((c) => c.id.equals(id))).getSingleOrNull();
  }

  /// 获取全部顶级 + 子分类（CSV 进货名称匹配）
  Future<List<Category>> getAllCategoriesFlat() async {
    final tops = await getTopLevelCategories();
    final all = <Category>[...tops];
    for (final t in tops) {
      all.addAll(await getChildCategories(t.id));
    }
    return all;
  }

  // ==================== Locations DAO ====================

  // 获取所有顶级位置（房间）
  Future<List<Location>> getTopLevelLocations() {
    return (select(locations)
          ..where((l) => l.parentId.isNull())
          ..orderBy([(l) => OrderingTerm(expression: l.sortOrder)]))
        .get();
  }

  // 获取指定父级的子位置
  Future<List<Location>> getChildLocations(int parentId) {
    return (select(locations)
          ..where((l) => l.parentId.equals(parentId))
          ..orderBy([(l) => OrderingTerm(expression: l.sortOrder)]))
        .get();
  }

  // 根据 ID 获取位置
  Future<Location?> getLocationById(int id) {
    return (select(locations)..where((l) => l.id.equals(id))).getSingleOrNull();
  }

  // 获取所有位置
  Future<List<Location>> getAllLocations() {
    return (select(locations)..orderBy([(l) => OrderingTerm(expression: l.sortOrder)])).get();
  }

  // ==================== Items DAO ====================

  // 获取所有物品（关联分类和位置）
  Future<List<Item>> getAllItems() async {
    try {
      return await (select(items)..orderBy([(i) => OrderingTerm(expression: i.createdAt, mode: OrderingMode.desc)])).get();
    } catch (e) {
      debugPrint('[DB] ERROR: 查询物品列表失败 - $e');
      return <Item>[];
    }
  }

  // 根据分类 ID 获取物品
  Future<List<Item>> getItemsByCategory(int categoryId) {
    return (select(items)
          ..where((i) => i.categoryId.equals(categoryId))
          ..orderBy([(i) => OrderingTerm(expression: i.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  // 根据 ID 获取物品
  Future<Item?> getItemById(int id) {
    return (select(items)..where((i) => i.id.equals(id))).getSingleOrNull();
  }

  /// 按服务端 item_id 查找本地物品（映射列优先）
  Future<Item?> getItemByServerItemId(int serverItemId) {
    return (select(items)
          ..where((i) => i.serverItemId.equals(serverItemId)))
        .getSingleOrNull();
  }

  /// 本地 itemId → 服务端 item_id（推送 usage 用）
  Future<int?> resolveServerItemId(int localItemId) async {
    final item = await getItemById(localItemId);
    if (item == null) {
      debugPrint('[ItemIdMap] WARN: 本地物品不存在 id=$localItemId');
      return null;
    }
    return item.serverItemId ?? item.id;
  }

  /// 服务端 item_id → 本地 itemId（拉取 usage 用）
  Future<int?> resolveLocalItemId(int serverItemId) async {
    final mapped = await getItemByServerItemId(serverItemId);
    if (mapped != null) return mapped.id;

    final direct = await getItemById(serverItemId);
    if (direct != null) return direct.id;

    _logMissingServerItemIdOnce(serverItemId);
    return null;
  }

  /// 同一 serverItemId 仅 WARN 一次，避免 usage 批量同步刷屏
  static final Set<int> _warnedMissingServerItemIds = {};

  static void _logMissingServerItemIdOnce(int serverItemId) {
    if (_warnedMissingServerItemIds.add(serverItemId)) {
      debugPrint(
        '[ItemIdMap] WARN: 未找到 serverItemId=$serverItemId 的本地物品（后续同 id 不再重复打印）',
      );
    }
  }

  /// 绑定本地物品与服务端 id
  Future<void> setItemServerItemId(int localItemId, int serverItemId) {
    return (update(items)..where((i) => i.id.equals(localItemId))).write(
      ItemsCompanion(
        serverItemId: Value(serverItemId),
        updatedAt: Value(DateTime.now()),
      ),
    );
  }

  /// 仅在未绑定时写入 serverItemId（兼容历史数据）
  Future<void> ensureItemServerItemId(int localItemId, int serverItemId) async {
    final item = await getItemById(localItemId);
    if (item == null || item.serverItemId != null) return;
    await setItemServerItemId(localItemId, serverItemId);
    debugPrint(
      '[ItemIdMap] INFO: 回填映射 local=$localItemId server=$serverItemId',
    );
  }

  // 插入物品并返回 ID
  Future<int> insertItem(ItemsCompanion item) {
    return into(items).insert(item);
  }

  // 更新物品
  Future<bool> updateItem(Item item) {
    return update(items).replace(item);
  }

  // 删除物品（同时清理关联数据）
  Future<void> deleteItem(int id) async {
    await (delete(items)..where((i) => i.id.equals(id))).go();
    // 删除关联的使用记录
    await (delete(usageRecords)..where((r) => r.itemId.equals(id))).go();
    // 清理购物清单中对该物品的关联
    await (update(shoppingList)..where((s) => s.relatedItemId.equals(id)))
        .write(const ShoppingListCompanion(relatedItemId: Value(null)));
  }

  // ==================== UsageRecords DAO ====================

  // 获取物品的使用记录
  Future<List<UsageRecord>> getUsageRecordsByItem(int itemId, {int limit = 10}) {
    return (select(usageRecords)
          ..where((r) => r.itemId.equals(itemId))
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.desc)])
          ..limit(limit))
        .get();
  }

  // 获取全部最近使用记录（用于同步去重）
  Future<List<UsageRecord>> getRecentUsageRecords({int limit = 1000}) {
    return (select(usageRecords)
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.desc)])
          ..limit(limit))
        .get();
  }

  /// B+ 日销：某时刻起的 usage 记录（可选 type 过滤）
  Future<List<UsageRecord>> getUsageRecordsSince(
    DateTime since, {
    int? type,
  }) {
    return (select(usageRecords)
          ..where((r) {
            var expr = r.createdAt.isBiggerOrEqualValue(since);
            if (type != null) {
              expr = expr & r.type.equals(type);
            }
            return expr;
          })
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  /// B+ 日销：单物品某时刻起的 usage 记录
  Future<List<UsageRecord>> getUsageRecordsByItemSince(
    int itemId,
    DateTime since,
  ) {
    return (select(usageRecords)
          ..where(
            (r) =>
                r.itemId.equals(itemId) &
                r.createdAt.isBiggerOrEqualValue(since),
          )
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  // 插入使用记录
  Future<int> insertUsageRecord(UsageRecordsCompanion record) {
    return into(usageRecords).insert(record);
  }

  /// 按本地 id 查询
  Future<UsageRecord?> getUsageRecordById(int id) {
    return (select(usageRecords)..where((r) => r.id.equals(id)))
        .getSingleOrNull();
  }

  /// 尚未同步到服务端的记录
  Future<List<UsageRecord>> getUnsyncedUsageRecords({int limit = 200}) {
    return (select(usageRecords)
          ..where((r) => r.serverRecordId.isNull())
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.asc)])
          ..limit(limit))
        .get();
  }

  /// 写入服务端记录 id
  Future<void> setUsageRecordServerId(int localId, int serverId) {
    return (update(usageRecords)..where((r) => r.id.equals(localId))).write(
      UsageRecordsCompanion(serverRecordId: Value(serverId)),
    );
  }

  // ==================== ShoppingList DAO ====================

  // 获取购物清单
  Future<List<ShoppingListData>> getShoppingList() {
    return (select(shoppingList)
          ..orderBy([(s) => OrderingTerm(expression: s.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  // 插入购物清单项
  Future<int> insertShoppingListItem(ShoppingListCompanion item) {
    return into(shoppingList).insert(item);
  }

  // ==================== AssistantMessages DAO ====================

  /// 插入一条问管管消息
  Future<int> insertAssistantMessage(AssistantMessagesCompanion message) {
    return into(assistantMessages).insert(message);
  }

  /// 按时间正序加载最近 N 条对话
  Future<List<AssistantMessage>> getAssistantMessages({int limit = 50}) {
    return (select(assistantMessages)
          ..orderBy([(m) => OrderingTerm(expression: m.createdAt, mode: OrderingMode.desc)])
          ..limit(limit))
        .get()
        .then((rows) => rows.reversed.toList());
  }

  /// 清空问管管对话记录
  Future<int> clearAssistantMessages() {
    return delete(assistantMessages).go();
  }

  /// 保留最近 keep 条，删除更早记录
  Future<void> trimAssistantMessages({int keep = 100}) async {
    final ids = await (select(assistantMessages)
          ..orderBy([(m) => OrderingTerm(expression: m.createdAt, mode: OrderingMode.asc)]))
        .map((m) => m.id)
        .get();
    if (ids.length <= keep) return;
    final toRemove = ids.sublist(0, ids.length - keep);
    await (delete(assistantMessages)..where((m) => m.id.isIn(toRemove))).go();
    debugPrint('[DB] INFO: 问管管记录裁剪 删除=${toRemove.length} 保留=$keep');
  }

  // ==================== FamilyMembers DAO ====================

  // 获取所有家庭成员
  Future<List<FamilyMember>> getFamilyMembers() {
    return (select(familyMembers)..orderBy([(m) => OrderingTerm(expression: m.createdAt)])).get();
  }

  // ==================== Locations Extended DAO ====================

  // 获取位置及其所有子位置
  Future<List<Location>> getLocationAndChildren(int parentId) async {
    final result = <Location>[];
    final children = await getChildLocations(parentId);
    for (final child in children) {
      result.add(child);
      result.addAll(await getLocationAndChildren(child.id));
    }
    return result;
  }

  // 获取位置下的物品数量（包括子位置）
  Future<int> getItemCountForLocation(int locationId) async {
    final location = await getLocationById(locationId);
    if (location == null) return 0;
    
    final childLocations = await getLocationAndChildren(locationId);
    final locationIds = [locationId] + childLocations.map((l) => l.id).toList();
    
    final count = await (select(items)
          ..where((i) => i.locationId.isIn(locationIds)))
        .get();
    
    return count.length;
  }

  // 获取指定位置下的物品（不包括子位置）
  Future<List<Item>> getItemsInLocation(int locationId) {
    return (select(items)
          ..where((i) => i.locationId.equals(locationId))
          ..orderBy([(i) => OrderingTerm(expression: i.expiryDate, mode: OrderingMode.asc)])
          ..where((i) => i.status.equals(0)))
        .get();
  }

  /// 获取指定位置及所有子位置下的使用中物品（盘点用）
  Future<List<Item>> getItemsInLocationTree(int locationId) async {
    final childLocations = await getLocationAndChildren(locationId);
    final locationIds = [locationId, ...childLocations.map((l) => l.id)];

    return (select(items)
          ..where((i) => i.locationId.isIn(locationIds))
          ..where((i) => i.status.equals(0))
          ..orderBy([(i) => OrderingTerm(expression: i.expiryDate, mode: OrderingMode.asc)]))
        .get();
  }

  // 插入新位置
  Future<int> insertLocation(LocationsCompanion location) {
    return into(locations).insert(location);
  }

  // 删除位置及其所有子位置
  Future<void> deleteLocationAndChildren(int locationId) async {
    final childLocations = await getLocationAndChildren(locationId);
    final locationIds = [locationId] + childLocations.map((l) => l.id).toList();
    
    await batch((batch) {
      batch.deleteWhere(locations, (l) => l.id.isIn(locationIds));
    });
  }

  // 更新位置排序
  Future<void> updateLocationSortOrder(int locationId, int sortOrder) {
    return (update(locations)..where((l) => l.id.equals(locationId)))
        .write(LocationsCompanion(sortOrder: Value(sortOrder)));
  }

  // ==================== Alerts DAO ====================

  // 获取过期提醒（status=0, 有过期日期, 即将过期）
  Future<List<Item>> getExpiryAlerts() {
    final today = DateTime.now();
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.expiryDate.isNotNull())
          ..where((i) => i.expiryDate.isSmallerOrEqualValue(today.add(Duration(days: 30)))))
        .get();
  }

  // 获取库存预警（status=0, 库存不足）
  Future<List<Item>> getStockAlerts() {
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.currentQuantity.isSmallerOrEqual(i.safetyStock)))
        .get();
  }

  // 获取补购提醒（status=1, 最近7天变为用完）
  Future<List<Item>> getRestockAlerts() {
    final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
    return (select(items)
          ..where((i) => i.status.equals(1))
          ..where((i) => i.updatedAt.isBiggerOrEqualValue(sevenDaysAgo)))
        .get();
  }

  // 获取保修提醒（status=0, 保修即将到期）
  Future<List<Item>> getWarrantyAlerts() {
    final today = DateTime.now();
    final thirtyDaysLater = today.add(const Duration(days: 30));
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.warrantyDate.isNotNull())
          ..where((i) => i.warrantyDate.isBetweenValues(today, thirtyDaysLater)))
        .get();
  }

  // 获取所有提醒数量（四类合计，不含已读/忽略）
  Future<int> getAlertCount() async {
    try {
      final alerts = await _collectAllAlertPairs();
      return alerts.length;
    } catch (e) {
      debugPrint('[DB] WARN: 获取提醒数量失败 - $e');
      return 0;
    }
  }

  /// 收集当前所有提醒（物品 + 类型）
  Future<List<(Item, String alertTypeKey)>> _collectAllAlertPairs() async {
    final List<(Item, String)> pairs = [];
    final expiryAlerts = await getExpiryAlerts();
    pairs.addAll(expiryAlerts.map((item) => (item, 'expiry')));
    final stockAlerts = await getStockAlerts();
    pairs.addAll(stockAlerts.map((item) => (item, 'stock')));
    final restockAlerts = await getRestockAlerts();
    pairs.addAll(restockAlerts.map((item) => (item, 'restock')));
    final warrantyAlerts = await getWarrantyAlerts();
    pairs.addAll(warrantyAlerts.map((item) => (item, 'warranty')));
    return pairs;
  }

  /// 查询某条提醒的已读/忽略状态
  Future<AlertReadState?> _getAlertReadState(
    int itemId,
    String alertType,
    int familyId,
  ) {
    return (select(alertReadStates)
          ..where((s) => s.itemId.equals(itemId))
          ..where((s) => s.alertType.equals(alertType))
          ..where((s) => s.familyId.equals(familyId)))
        .getSingleOrNull();
  }

  /// 是否未读（未标记已读且未忽略）
  Future<bool> isAlertUnread(int itemId, String alertType, int familyId) async {
    final state = await _getAlertReadState(itemId, alertType, familyId);
    if (state == null) return true;
    if (state.ignored) return false;
    if (state.readAt != null) return false;
    return true;
  }

  /// 未读提醒数量（Badge 真源）
  Future<int> getUnreadAlertCount(int familyId) async {
    try {
      final pairs = await _collectAllAlertPairs();
      var count = 0;
      for (final (item, typeKey) in pairs) {
        if (await isAlertUnread(item.id, typeKey, familyId)) {
          count++;
        }
      }
      return count;
    } catch (e) {
      debugPrint('[DB] ERROR: 获取未读提醒数量失败 - $e');
      return 0;
    }
  }

  /// 未读提醒列表（通知中心，按紧急度降序）
  Future<List<(Item, String alertTypeKey, int urgency)>> getUnreadNotifications(
    int familyId, {
    int limit = 20,
  }) async {
    final pairs = await _collectAllAlertPairs();
    final unread = <(Item, String, int)>[];
    for (final (item, typeKey) in pairs) {
      if (await isAlertUnread(item.id, typeKey, familyId)) {
        final type = alertTypeFromKey(typeKey);
        final urgency = getAlertDisplayInfo(item, type).urgency;
        unread.add((item, typeKey, urgency));
      }
    }
    unread.sort((a, b) => b.$3.compareTo(a.$3));
    if (unread.length > limit) {
      return unread.sublist(0, limit);
    }
    return unread;
  }

  /// 提醒 Tab 列表（排除已忽略，已读仍展示）
  Future<List<(Item, String alertTypeKey)>> getAlertsForDisplay(
    int familyId, {
    String? typeFilter,
    bool excludeIgnored = true,
  }) async {
    var pairs = await _collectAllAlertPairs();
    if (typeFilter != null && typeFilter != 'all') {
      pairs = pairs.where((p) => p.$2 == typeFilter).toList();
    }
    if (!excludeIgnored) return pairs;

    final filtered = <(Item, String)>[];
    for (final (item, typeKey) in pairs) {
      final state = await _getAlertReadState(item.id, typeKey, familyId);
      if (state?.ignored == true) continue;
      filtered.add((item, typeKey));
    }
    return filtered;
  }

  /// 标记单条提醒已读
  Future<void> markAlertRead(int itemId, String alertType, int familyId) async {
    final existing = await _getAlertReadState(itemId, alertType, familyId);
    if (existing != null) {
      await (update(alertReadStates)..where((s) => s.id.equals(existing.id))).write(
        AlertReadStatesCompanion(
          readAt: Value(DateTime.now()),
          ignored: const Value(false),
        ),
      );
    } else {
      await into(alertReadStates).insert(
        AlertReadStatesCompanion.insert(
          itemId: itemId,
          alertType: alertType,
          familyId: Value(familyId),
          readAt: Value(DateTime.now()),
        ),
      );
    }
    debugPrint('[DB] INFO: 提醒已读 itemId=$itemId type=$alertType familyId=$familyId');
  }

  /// 标记全部当前提醒为已读
  Future<void> markAllAlertsRead(int familyId) async {
    final pairs = await _collectAllAlertPairs();
    for (final (item, typeKey) in pairs) {
      await markAlertRead(item.id, typeKey, familyId);
    }
    debugPrint('[DB] INFO: 全部提醒已读 familyId=$familyId count=${pairs.length}');
  }

  /// 忽略单条提醒（持久化）
  Future<void> ignoreAlert(int itemId, String alertType, int familyId) async {
    final existing = await _getAlertReadState(itemId, alertType, familyId);
    if (existing != null) {
      await (update(alertReadStates)..where((s) => s.id.equals(existing.id))).write(
        const AlertReadStatesCompanion(ignored: Value(true)),
      );
    } else {
      await into(alertReadStates).insert(
        AlertReadStatesCompanion.insert(
          itemId: itemId,
          alertType: alertType,
          familyId: Value(familyId),
          ignored: const Value(true),
        ),
      );
    }
    debugPrint('[DB] INFO: 提醒已忽略 itemId=$itemId type=$alertType');
  }
  
  // 预设数据插入
  Future<void> seedData() async {
    final hasCategories = await (select(categories)..limit(1)).get().then((rows) => rows.isNotEmpty);
    if (!hasCategories) {
      await batch((batch) {
        batch.insertAll(categories, [
          // ==================== 一级分类 ====================
          // id=1
          CategoriesCompanion.insert(name: '食品饮料', icon: '🍎', color: '#FF8A65', isSystem: const Value(true), sortOrder: const Value(1)),
          // id=2
          CategoriesCompanion.insert(name: '日用清洁', icon: '🧹', color: '#4DB6AC', isSystem: const Value(true), sortOrder: const Value(2)),
          // id=3
          CategoriesCompanion.insert(name: '个护美妆', icon: '🧴', color: '#F06292', isSystem: const Value(true), sortOrder: const Value(3)),
          // id=4
          CategoriesCompanion.insert(name: '药品保健', icon: '💊', color: '#7986CB', isSystem: const Value(true), sortOrder: const Value(4)),
          // id=5
          CategoriesCompanion.insert(name: '家用电器', icon: '📺', color: '#FFD54F', isSystem: const Value(true), sortOrder: const Value(5)),
          // id=6
          CategoriesCompanion.insert(name: '衣物鞋帽', icon: '👕', color: '#EF5350', isSystem: const Value(true), sortOrder: const Value(6)),
          // id=7
          CategoriesCompanion.insert(name: '家居日用', icon: '🛋️', color: '#8D6E63', isSystem: const Value(true), sortOrder: const Value(7)),
          // id=8
          CategoriesCompanion.insert(name: '书籍文具', icon: '📚', color: '#78909C', isSystem: const Value(true), sortOrder: const Value(8)),
          // id=9
          CategoriesCompanion.insert(name: '数码配件', icon: '🔌', color: '#42A5F5', isSystem: const Value(true), sortOrder: const Value(9)),
          // id=10
          CategoriesCompanion.insert(name: '宠物用品', icon: '🐾', color: '#FFA726', isSystem: const Value(true), sortOrder: const Value(10)),
          // id=11
          CategoriesCompanion.insert(name: '母婴用品', icon: '🍼', color: '#EC407A', isSystem: const Value(true), sortOrder: const Value(11)),
          // id=12
          CategoriesCompanion.insert(name: '运动户外', icon: '⚽', color: '#66BB6A', isSystem: const Value(true), sortOrder: const Value(12)),
          // id=13
          CategoriesCompanion.insert(name: '汽车用品', icon: '🚗', color: '#5C6BC0', isSystem: const Value(true), sortOrder: const Value(13)),
          // id=14
          CategoriesCompanion.insert(name: '工具五金', icon: '🔧', color: '#795548', isSystem: const Value(true), sortOrder: const Value(14)),
          // id=15
          CategoriesCompanion.insert(name: '其他', icon: '📦', color: '#A1887F', isSystem: const Value(true), sortOrder: const Value(99)),

          // ==================== 食品饮料 ====================
          CategoriesCompanion.insert(name: '乳制品', icon: '🥛', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '肉禽蛋', icon: '🥩', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '海鲜水产', icon: '🦐', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '蔬菜水果', icon: '🥦', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '零食糖果', icon: '🍪', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '饮料冲调', icon: '🥤', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(6)),
          CategoriesCompanion.insert(name: '调味品', icon: '🧂', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(7)),
          CategoriesCompanion.insert(name: '米面粮油', icon: '🌾', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(8)),
          CategoriesCompanion.insert(name: '方便速食', icon: '🍜', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(9)),
          CategoriesCompanion.insert(name: '烘焙原料', icon: '🍞', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(10)),
          CategoriesCompanion.insert(name: '茶/咖啡', icon: '☕', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(11)),

          // ==================== 日用清洁 ====================
          CategoriesCompanion.insert(name: '洗衣/柔顺剂', icon: '🧺', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '厨房清洁', icon: '🧼', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '卫浴清洁', icon: '🚽', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '纸巾/湿巾', icon: '🧻', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '垃圾袋/保鲜袋', icon: '🗑️', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '消杀/驱虫', icon: '🪰', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(6)),
          CategoriesCompanion.insert(name: '抹布/拖把', icon: '🪣', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(7)),

          // ==================== 个护美妆 ====================
          CategoriesCompanion.insert(name: '洗发/护发', icon: '💇', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '沐浴/香皂', icon: '🚿', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '口腔护理', icon: '🪥', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '面部护肤', icon: '✨', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '彩妆', icon: '💄', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '男士护理', icon: '🪒', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(6)),
          CategoriesCompanion.insert(name: '卫生巾/棉条', icon: '🩸', color: '#F06292', parentId: const Value(3), isSystem: const Value(true), sortOrder: const Value(7)),

          // ==================== 药品保健 ====================
          CategoriesCompanion.insert(name: '感冒/退烧', icon: '🤒', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '肠胃消化', icon: '💊', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '外伤/创可贴', icon: '🩹', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '维生素/保健品', icon: '🌿', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '医疗器械', icon: '🌡️', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '中药/药材', icon: '🫖', color: '#7986CB', parentId: const Value(4), isSystem: const Value(true), sortOrder: const Value(6)),

          // ==================== 家用电器 ====================
          CategoriesCompanion.insert(name: '厨房电器', icon: '🍳', color: '#FFD54F', parentId: const Value(5), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '清洁电器', icon: '🧹', color: '#FFD54F', parentId: const Value(5), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '个护电器', icon: '💇', color: '#FFD54F', parentId: const Value(5), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '空调/暖气', icon: '🌡️', color: '#FFD54F', parentId: const Value(5), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '灯具/灯泡', icon: '💡', color: '#FFD54F', parentId: const Value(5), isSystem: const Value(true), sortOrder: const Value(5)),

          // ==================== 衣物鞋帽 ====================
          CategoriesCompanion.insert(name: '上衣', icon: '👔', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '裤子/裙子', icon: '👖', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '外套/大衣', icon: '🧥', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '鞋/靴', icon: '👟', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '内衣/袜子', icon: '🧦', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '围巾/帽子', icon: '🧣', color: '#EF5350', parentId: const Value(6), isSystem: const Value(true), sortOrder: const Value(6)),

          // ==================== 家居日用 ====================
          CategoriesCompanion.insert(name: '床上用品', icon: '🛏️', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '收纳/整理箱', icon: '📦', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '毛巾/浴巾', icon: '🛁', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '装饰/相框', icon: '🖼️', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '杯具/餐具', icon: '🍽️', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '一次性用品', icon: '🥡', color: '#8D6E63', parentId: const Value(7), isSystem: const Value(true), sortOrder: const Value(6)),

          // ==================== 书籍文具 ====================
          CategoriesCompanion.insert(name: '小说文学', icon: '📖', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '专业/工具书', icon: '📕', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '杂志/漫画', icon: '📰', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '笔类', icon: '🖊️', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '本册/纸张', icon: '📓', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '桌面文具', icon: '📎', color: '#78909C', parentId: const Value(8), isSystem: const Value(true), sortOrder: const Value(6)),

          // ==================== 数码配件 ====================
          CategoriesCompanion.insert(name: '手机壳/膜', icon: '📱', color: '#42A5F5', parentId: const Value(9), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '数据线/充电头', icon: '🔋', color: '#42A5F5', parentId: const Value(9), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '耳机/音箱', icon: '🎧', color: '#42A5F5', parentId: const Value(9), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: 'U盘/硬盘', icon: '💾', color: '#42A5F5', parentId: const Value(9), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '相机/镜头', icon: '📷', color: '#42A5F5', parentId: const Value(9), isSystem: const Value(true), sortOrder: const Value(5)),

          // ==================== 宠物用品 ====================
          CategoriesCompanion.insert(name: '宠物食品', icon: '🦴', color: '#FFA726', parentId: const Value(10), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '猫砂/尿垫', icon: '🐱', color: '#FFA726', parentId: const Value(10), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '宠物药品', icon: '💊', color: '#FFA726', parentId: const Value(10), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '玩具/用品', icon: '🎾', color: '#FFA726', parentId: const Value(10), isSystem: const Value(true), sortOrder: const Value(4)),

          // ==================== 母婴用品 ====================
          CategoriesCompanion.insert(name: '奶粉/辅食', icon: '🍼', color: '#EC407A', parentId: const Value(11), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '纸尿裤', icon: '👶', color: '#EC407A', parentId: const Value(11), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '玩具/绘本', icon: '🧸', color: '#EC407A', parentId: const Value(11), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '孕产用品', icon: '🤰', color: '#EC407A', parentId: const Value(11), isSystem: const Value(true), sortOrder: const Value(4)),

          // ==================== 运动户外 ====================
          CategoriesCompanion.insert(name: '健身器材', icon: '🏋️', color: '#66BB6A', parentId: const Value(12), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '球类/拍类', icon: '🏸', color: '#66BB6A', parentId: const Value(12), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '露营/户外', icon: '🏕️', color: '#66BB6A', parentId: const Value(12), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '游泳/水上', icon: '🏊', color: '#66BB6A', parentId: const Value(12), isSystem: const Value(true), sortOrder: const Value(4)),

          // ==================== 汽车用品 ====================
          CategoriesCompanion.insert(name: '洗车/打蜡', icon: '🧽', color: '#5C6BC0', parentId: const Value(13), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '车载电子/记录仪', icon: '📻', color: '#5C6BC0', parentId: const Value(13), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '应急安全', icon: '⚠️', color: '#5C6BC0', parentId: const Value(13), isSystem: const Value(true), sortOrder: const Value(3)),

          // ==================== 工具五金 ====================
          CategoriesCompanion.insert(name: '手动工具', icon: '🔨', color: '#795548', parentId: const Value(14), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '电动工具', icon: '🪚', color: '#795548', parentId: const Value(14), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '螺丝/钉子等', icon: '🔩', color: '#795548', parentId: const Value(14), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '胶带/胶水', icon: '🧴', color: '#795548', parentId: const Value(14), isSystem: const Value(true), sortOrder: const Value(4)),
        ]);
      });
    }
    
    final hasLocations = await (select(locations)..limit(1)).get().then((rows) => rows.isNotEmpty);
    if (!hasLocations) {
      await batch((batch) {
        batch.insertAll(locations, [
          LocationsCompanion.insert(name: '厨房', icon: const Value('🍳'), level: const Value(1), fullPath: '厨房', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '卫生间', icon: const Value('🛁'), level: const Value(1), fullPath: '卫生间', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '客厅', icon: const Value('🛋️'), level: const Value(1), fullPath: '客厅', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '主卧', icon: const Value('🛏️'), level: const Value(1), fullPath: '主卧', sortOrder: const Value(4)),
          LocationsCompanion.insert(name: '次卧', icon: const Value('🛏️'), level: const Value(1), fullPath: '次卧', sortOrder: const Value(5)),
          LocationsCompanion.insert(name: '阳台', icon: const Value('☀️'), level: const Value(1), fullPath: '阳台', sortOrder: const Value(6)),
          
          LocationsCompanion.insert(name: '冰箱', icon: const Value('❄️'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/冰箱', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '吊柜', icon: const Value('🏠'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/吊柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '调料架', icon: const Value('🧂'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/调料架', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '水槽下方', icon: const Value('🚰'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/水槽下方', sortOrder: const Value(4)),
          LocationsCompanion.insert(name: '台面', icon: const Value('🪟'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/台面', sortOrder: const Value(5)),
          
          LocationsCompanion.insert(name: '冷藏层', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/冷藏层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '冷冻层', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/冷冻层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '门侧', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/门侧', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '一层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/一层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '二层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/二层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '三层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/三层', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '洗漱台', icon: const Value('🚿'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/洗漱台', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '浴室柜', icon: const Value('🗄️'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/浴室柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '马桶旁', icon: const Value('🚽'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/马桶旁', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '台面', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/台面', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '镜柜', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/镜柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '下方', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/下方', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '电视柜', icon: const Value('📺'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/电视柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '茶几', icon: const Value('🪑'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/茶几', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '书架', icon: const Value('📚'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/书架', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '上方', parentId: const Value(22), level: const Value(3), fullPath: '客厅/茶几/上方', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '下方', parentId: const Value(22), level: const Value(3), fullPath: '客厅/茶几/下方', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '衣柜', icon: const Value('🗄️'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/衣柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '床头柜', icon: const Value('🛏️'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/床头柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '梳妆台', icon: const Value('🪞'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/梳妆台', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '上层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/上层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '中层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/中层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '下层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/下层', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '抽屉', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/抽屉', sortOrder: const Value(4)),
          
          LocationsCompanion.insert(name: '台面', parentId: const Value(27), level: const Value(3), fullPath: '主卧/床头柜/台面', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '抽屉', parentId: const Value(27), level: const Value(3), fullPath: '主卧/床头柜/抽屉', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '衣柜', icon: const Value('🗄️'), parentId: const Value(5), level: const Value(2), fullPath: '次卧/衣柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '书桌', icon: const Value('🖥️'), parentId: const Value(5), level: const Value(2), fullPath: '次卧/书桌', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '储物柜', icon: const Value('📦'), parentId: const Value(6), level: const Value(2), fullPath: '阳台/储物柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '晾衣区', icon: const Value('👕'), parentId: const Value(6), level: const Value(2), fullPath: '阳台/晾衣区', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '上层', parentId: const Value(36), level: const Value(3), fullPath: '阳台/储物柜/上层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '下层', parentId: const Value(36), level: const Value(3), fullPath: '阳台/储物柜/下层', sortOrder: const Value(2)),
        ]);
      });
    }
  }

  /// 是否已有物品（有则不再替换预设模板）
  Future<bool> hasAnyItems() async {
    final rows = await (select(items)..limit(1)).get();
    return rows.isNotEmpty;
  }

  /// 是否已存在指定名称的分类
  Future<bool> hasCategoryNamed(String name) async {
    final rows = await (select(categories)
          ..where((c) => c.name.equals(name))
          ..limit(1))
        .get();
    return rows.isNotEmpty;
  }

  /// 清空本地分类与位置（仅用于无物品时的模板切换）
  Future<void> clearCategoriesAndLocations() async {
    await delete(locations).go();
    await delete(categories).go();
    debugPrint('[DB] INFO: 已清空本地分类与位置');
  }

  /// B3 — 店铺空间首次 seed：无物品且未应用过店铺模板时写入
  Future<void> seedShopPresetIfNeeded() async {
    if (await hasAnyItems()) {
      debugPrint('[DB] WARN: 已有物品，跳过店铺模板 seed');
      return;
    }
    if (await hasCategoryNamed(SpaceShopSeedData.markerCategoryName)) {
      debugPrint('[DB] INFO: 店铺模板已存在，跳过');
      return;
    }

    debugPrint('[DB] INFO: 应用店铺默认分类与位置模板');
    await transaction(() async {
      await clearCategoriesAndLocations();
      await batch((batch) {
        batch.insertAll(categories, SpaceShopSeedData.categoryCompanions());
        batch.insertAll(locations, SpaceShopSeedData.locationCompanions());
      });
    });
  }
}