import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift_sqflite/drift_sqflite.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as path;
part 'app_database.g.dart';

// 分类表
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get icon => text()();
  TextColumn get color => text()();
  IntColumn get parentId => integer().nullable()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  BoolColumn get isSystem => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 位置表
class Locations extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get icon => text().nullable()();
  IntColumn get parentId => integer().nullable()();
  IntColumn get level => integer().withDefault(const Constant(1))();
  TextColumn get fullPath => text()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 物品表
class Items extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get brand => text().nullable()();
  TextColumn get specification => text().nullable()();
  TextColumn get barcode => text().nullable()();
  IntColumn get categoryId => integer()();
  IntColumn get locationId => integer().nullable()();
  RealColumn get purchasePrice => real().nullable()();
  IntColumn get purchaseQuantity => integer().withDefault(const Constant(1))();
  RealColumn get currentQuantity => real().withDefault(const Constant(1))();
  TextColumn get unit => text().withDefault(const Constant('件'))();
  RealColumn get safetyStock => real().withDefault(const Constant(1))();
  DateTimeColumn get purchaseDate => dateTime().nullable()();
  TextColumn get purchaseChannel => text().nullable()();
  DateTimeColumn get productionDate => dateTime().nullable()();
  DateTimeColumn get expiryDate => dateTime().nullable()();
  IntColumn get shelfLifeDays => integer().nullable()();
  DateTimeColumn get openedDate => dateTime().nullable()();
  IntColumn get afterOpenDays => integer().nullable()();
  DateTimeColumn get warrantyDate => dateTime().nullable()();
  IntColumn get expiryAlertDays => integer().withDefault(const Constant(3))();
  BoolColumn get stockAlert => boolean().withDefault(const Constant(true))();
  TextColumn get images => text().nullable()();
  TextColumn get notes => text().nullable()();
  IntColumn get status => integer().withDefault(const Constant(0))();
  RealColumn get avgDailyConsumption => real().nullable()();
  DateTimeColumn get predictedEmptyDate => dateTime().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

// 使用记录表
class UsageRecords extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get itemId => integer()();
  IntColumn get type => integer()(); // 0入库/1使用/2丢弃/3移动/4调整
  RealColumn get quantity => real()();
  RealColumn get remainingQuantity => real()();
  TextColumn get operatorName => text().nullable()();
  TextColumn get notes => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 购物清单表
class ShoppingList extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  IntColumn get relatedItemId => integer().nullable()();
  RealColumn get quantity => real().withDefault(const Constant(1))();
  TextColumn get unit => text().withDefault(const Constant('件'))();
  RealColumn get estimatedPrice => real().nullable()();
  BoolColumn get isPurchased => boolean().withDefault(const Constant(false))();
  BoolColumn get isAutoGenerated => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// 家庭成员表
class FamilyMembers extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  TextColumn get avatar => text().nullable()();
  TextColumn get role => text().withDefault(const Constant('member'))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

@DriftDatabase(
  tables: [
    Categories,
    Locations,
    Items,
    UsageRecords,
    ShoppingList,
    FamilyMembers,
  ],
)
class AppDatabase extends _$AppDatabase {
  static final AppDatabase _instance = AppDatabase._internal();

  factory AppDatabase() => _instance;

  AppDatabase._internal() : super(_openConnection());
  
  @override
  int get schemaVersion => 1;
  
  Future<void>? _seedDataFuture;
  
  Future<void> ensureInitialized() {
    if (_seedDataFuture == null) {
      _seedDataFuture = seedData();
    }
    return _seedDataFuture!;
  }
  
  static LazyDatabase _openConnection() {
    return LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(path.join(dbFolder.path, 'homestock.db'));
      return SqfliteQueryExecutor.inDatabaseFolder(path: 'homestock.db');
    });
  }

  // ==================== Categories DAO ====================
  
  // 获取所有顶级分类
  Future<List<Category>> getTopLevelCategories() {
    return (select(categories)
          ..where((c) => c.parentId.isNull())
          ..orderBy([(c) => OrderingTerm(expression: c.sortOrder)]))
        .get();
  }

  // 获取指定父级的子分类
  Future<List<Category>> getChildCategories(int parentId) {
    return (select(categories)
          ..where((c) => c.parentId.equals(parentId))
          ..orderBy([(c) => OrderingTerm(expression: c.sortOrder)]))
        .get();
  }

  // 根据 ID 获取分类
  Future<Category?> getCategoryById(int id) {
    return (select(categories)..where((c) => c.id.equals(id))).getSingleOrNull();
  }

  // ==================== Locations DAO ====================

  // 获取所有顶级位置（房间）
  Future<List<Location>> getTopLevelLocations() {
    return (select(locations)
          ..where((l) => l.parentId.isNull())
          ..orderBy([(l) => OrderingTerm(expression: l.sortOrder)]))
        .get();
  }

  // 获取指定父级的子位置
  Future<List<Location>> getChildLocations(int parentId) {
    return (select(locations)
          ..where((l) => l.parentId.equals(parentId))
          ..orderBy([(l) => OrderingTerm(expression: l.sortOrder)]))
        .get();
  }

  // 根据 ID 获取位置
  Future<Location?> getLocationById(int id) {
    return (select(locations)..where((l) => l.id.equals(id))).getSingleOrNull();
  }

  // 获取所有位置
  Future<List<Location>> getAllLocations() {
    return (select(locations)..orderBy([(l) => OrderingTerm(expression: l.sortOrder)])).get();
  }

  // ==================== Items DAO ====================

  // 获取所有物品（关联分类和位置）
  Future<List<Item>> getAllItems() {
    return (select(items)..orderBy([(i) => OrderingTerm(expression: i.createdAt, mode: OrderingMode.desc)])).get();
  }

  // 根据分类 ID 获取物品
  Future<List<Item>> getItemsByCategory(int categoryId) {
    return (select(items)
          ..where((i) => i.categoryId.equals(categoryId))
          ..orderBy([(i) => OrderingTerm(expression: i.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  // 根据 ID 获取物品
  Future<Item?> getItemById(int id) {
    return (select(items)..where((i) => i.id.equals(id))).getSingleOrNull();
  }

  // 插入物品并返回 ID
  Future<int> insertItem(ItemsCompanion item) {
    return into(items).insert(item);
  }

  // 更新物品
  Future<bool> updateItem(Item item) {
    return update(items).replace(item);
  }

  // 删除物品（同时清理关联数据）
  Future<void> deleteItem(int id) async {
    await (delete(items)..where((i) => i.id.equals(id))).go();
    // 删除关联的使用记录
    await (delete(usageRecords)..where((r) => r.itemId.equals(id))).go();
    // 清理购物清单中对该物品的关联
    await (update(shoppingList)..where((s) => s.relatedItemId.equals(id)))
        .write(const ShoppingListCompanion(relatedItemId: Value(null)));
  }

  // ==================== UsageRecords DAO ====================

  // 获取物品的使用记录
  Future<List<UsageRecord>> getUsageRecordsByItem(int itemId, {int limit = 10}) {
    return (select(usageRecords)
          ..where((r) => r.itemId.equals(itemId))
          ..orderBy([(r) => OrderingTerm(expression: r.createdAt, mode: OrderingMode.desc)])
          ..limit(limit))
        .get();
  }

  // 插入使用记录
  Future<int> insertUsageRecord(UsageRecordsCompanion record) {
    return into(usageRecords).insert(record);
  }

  // ==================== ShoppingList DAO ====================

  // 获取购物清单
  Future<List<ShoppingListData>> getShoppingList() {
    return (select(shoppingList)
          ..orderBy([(s) => OrderingTerm(expression: s.createdAt, mode: OrderingMode.desc)]))
        .get();
  }

  // 插入购物清单项
  Future<int> insertShoppingListItem(ShoppingListCompanion item) {
    return into(shoppingList).insert(item);
  }

  // ==================== FamilyMembers DAO ====================

  // 获取所有家庭成员
  Future<List<FamilyMember>> getFamilyMembers() {
    return (select(familyMembers)..orderBy([(m) => OrderingTerm(expression: m.createdAt)])).get();
  }

  // ==================== Locations Extended DAO ====================

  // 获取位置及其所有子位置
  Future<List<Location>> getLocationAndChildren(int parentId) async {
    final result = <Location>[];
    final children = await getChildLocations(parentId);
    for (final child in children) {
      result.add(child);
      result.addAll(await getLocationAndChildren(child.id));
    }
    return result;
  }

  // 获取位置下的物品数量（包括子位置）
  Future<int> getItemCountForLocation(int locationId) async {
    final location = await getLocationById(locationId);
    if (location == null) return 0;
    
    final childLocations = await getLocationAndChildren(locationId);
    final locationIds = [locationId] + childLocations.map((l) => l.id).toList();
    
    final count = await (select(items)
          ..where((i) => i.locationId.isIn(locationIds)))
        .get();
    
    return count.length;
  }

  // 获取指定位置下的物品（不包括子位置）
  Future<List<Item>> getItemsInLocation(int locationId) {
    return (select(items)
          ..where((i) => i.locationId.equals(locationId))
          ..orderBy([(i) => OrderingTerm(expression: i.expiryDate, mode: OrderingMode.asc)])
          ..where((i) => i.status.equals(0)))
        .get();
  }

  // 插入新位置
  Future<int> insertLocation(LocationsCompanion location) {
    return into(locations).insert(location);
  }

  // 删除位置及其所有子位置
  Future<void> deleteLocationAndChildren(int locationId) async {
    final childLocations = await getLocationAndChildren(locationId);
    final locationIds = [locationId] + childLocations.map((l) => l.id).toList();
    
    await batch((batch) {
      batch.deleteWhere(locations, (l) => l.id.isIn(locationIds));
    });
  }

  // 更新位置排序
  Future<void> updateLocationSortOrder(int locationId, int sortOrder) {
    return (update(locations)..where((l) => l.id.equals(locationId)))
        .write(LocationsCompanion(sortOrder: Value(sortOrder)));
  }

  // ==================== Alerts DAO ====================

  // 获取过期提醒（status=0, 有过期日期, 即将过期）
  Future<List<Item>> getExpiryAlerts() {
    final today = DateTime.now();
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.expiryDate.isNotNull())
          ..where((i) => i.expiryDate.isSmallerOrEqualValue(today.add(Duration(days: 30)))))
        .get();
  }

  // 获取库存预警（status=0, 库存不足）
  Future<List<Item>> getStockAlerts() {
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.currentQuantity.isSmallerOrEqual(i.safetyStock)))
        .get();
  }

  // 获取补购提醒（status=1, 最近7天变为用完）
  Future<List<Item>> getRestockAlerts() {
    final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
    return (select(items)
          ..where((i) => i.status.equals(1))
          ..where((i) => i.updatedAt.isBiggerOrEqualValue(sevenDaysAgo)))
        .get();
  }

  // 获取保修提醒（status=0, 保修即将到期）
  Future<List<Item>> getWarrantyAlerts() {
    final today = DateTime.now();
    final thirtyDaysLater = today.add(const Duration(days: 30));
    return (select(items)
          ..where((i) => i.status.equals(0))
          ..where((i) => i.warrantyDate.isNotNull())
          ..where((i) => i.warrantyDate.isBetweenValues(today, thirtyDaysLater)))
        .get();
  }

  // 获取所有提醒数量（过期+库存）
  Future<int> getAlertCount() async {
    final expiryCount = await getExpiryAlerts();
    final stockCount = await getStockAlerts();
    return expiryCount.length + stockCount.length;
  }
  
  // 预设数据插入
  Future<void> seedData() async {
    final hasCategories = await (select(categories)..limit(1)).get().then((rows) => rows.isNotEmpty);
    if (!hasCategories) {
      await batch((batch) {
        batch.insertAll(categories, [
          CategoriesCompanion.insert(name: '食品饮料', icon: '🍎', color: '#FF8A65', isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '日用清洁', icon: '🧹', color: '#4DB6AC', isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '个护美妆', icon: '🧴', color: '#F06292', isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '药品保健', icon: '💊', color: '#7986CB', isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '家用电器', icon: '📺', color: '#FFD54F', isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '衣物鞋帽', icon: '👕', color: '#F06292', isSystem: const Value(true), sortOrder: const Value(6)),
          CategoriesCompanion.insert(name: '其他', icon: '📦', color: '#A1887F', isSystem: const Value(true), sortOrder: const Value(7)),
          
          CategoriesCompanion.insert(name: '乳制品', icon: '🥛', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '肉类', icon: '🥩', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '蔬果', icon: '🥦', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '零食', icon: '🍪', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(4)),
          CategoriesCompanion.insert(name: '饮品', icon: '🥤', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(5)),
          CategoriesCompanion.insert(name: '调味品', icon: '🧂', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(6)),
          CategoriesCompanion.insert(name: '粮油', icon: '🌾', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(7)),
          CategoriesCompanion.insert(name: '速食', icon: '🍜', color: '#FF8A65', parentId: const Value(1), isSystem: const Value(true), sortOrder: const Value(8)),
          
          CategoriesCompanion.insert(name: '洗衣', icon: '🧺', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(1)),
          CategoriesCompanion.insert(name: '厨房清洁', icon: '🧼', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(2)),
          CategoriesCompanion.insert(name: '纸巾', icon: '🧻', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(3)),
          CategoriesCompanion.insert(name: '垃圾袋', icon: '🗑️', color: '#4DB6AC', parentId: const Value(2), isSystem: const Value(true), sortOrder: const Value(4)),
        ]);
      });
    }
    
    final hasLocations = await (select(locations)..limit(1)).get().then((rows) => rows.isNotEmpty);
    if (!hasLocations) {
      await batch((batch) {
        batch.insertAll(locations, [
          LocationsCompanion.insert(name: '厨房', icon: const Value('🍳'), level: const Value(1), fullPath: '厨房', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '卫生间', icon: const Value('🛁'), level: const Value(1), fullPath: '卫生间', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '客厅', icon: const Value('🛋️'), level: const Value(1), fullPath: '客厅', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '主卧', icon: const Value('🛏️'), level: const Value(1), fullPath: '主卧', sortOrder: const Value(4)),
          LocationsCompanion.insert(name: '次卧', icon: const Value('🛏️'), level: const Value(1), fullPath: '次卧', sortOrder: const Value(5)),
          LocationsCompanion.insert(name: '阳台', icon: const Value('☀️'), level: const Value(1), fullPath: '阳台', sortOrder: const Value(6)),
          
          LocationsCompanion.insert(name: '冰箱', icon: const Value('❄️'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/冰箱', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '吊柜', icon: const Value('🏠'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/吊柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '调料架', icon: const Value('🧂'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/调料架', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '水槽下方', icon: const Value('🚰'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/水槽下方', sortOrder: const Value(4)),
          LocationsCompanion.insert(name: '台面', icon: const Value('🪟'), parentId: const Value(1), level: const Value(2), fullPath: '厨房/台面', sortOrder: const Value(5)),
          
          LocationsCompanion.insert(name: '冷藏层', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/冷藏层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '冷冻层', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/冷冻层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '门侧', parentId: const Value(7), level: const Value(3), fullPath: '厨房/冰箱/门侧', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '一层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/一层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '二层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/二层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '三层', parentId: const Value(8), level: const Value(3), fullPath: '厨房/吊柜/三层', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '洗漱台', icon: const Value('🚿'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/洗漱台', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '浴室柜', icon: const Value('🗄️'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/浴室柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '马桶旁', icon: const Value('🚽'), parentId: const Value(2), level: const Value(2), fullPath: '卫生间/马桶旁', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '台面', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/台面', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '镜柜', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/镜柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '下方', parentId: const Value(16), level: const Value(3), fullPath: '卫生间/洗漱台/下方', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '电视柜', icon: const Value('📺'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/电视柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '茶几', icon: const Value('🪑'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/茶几', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '书架', icon: const Value('📚'), parentId: const Value(3), level: const Value(2), fullPath: '客厅/书架', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '上方', parentId: const Value(22), level: const Value(3), fullPath: '客厅/茶几/上方', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '下方', parentId: const Value(22), level: const Value(3), fullPath: '客厅/茶几/下方', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '衣柜', icon: const Value('🗄️'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/衣柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '床头柜', icon: const Value('🛏️'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/床头柜', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '梳妆台', icon: const Value('🪞'), parentId: const Value(4), level: const Value(2), fullPath: '主卧/梳妆台', sortOrder: const Value(3)),
          
          LocationsCompanion.insert(name: '上层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/上层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '中层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/中层', sortOrder: const Value(2)),
          LocationsCompanion.insert(name: '下层', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/下层', sortOrder: const Value(3)),
          LocationsCompanion.insert(name: '抽屉', parentId: const Value(26), level: const Value(3), fullPath: '主卧/衣柜/抽屉', sortOrder: const Value(4)),
          
          LocationsCompanion.insert(name: '台面', parentId: const Value(27), level: const Value(3), fullPath: '主卧/床头柜/台面', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '抽屉', parentId: const Value(27), level: const Value(3), fullPath: '主卧/床头柜/抽屉', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '衣柜', icon: const Value('🗄️'), parentId: const Value(5), level: const Value(2), fullPath: '次卧/衣柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '书桌', icon: const Value('🖥️'), parentId: const Value(5), level: const Value(2), fullPath: '次卧/书桌', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '储物柜', icon: const Value('📦'), parentId: const Value(6), level: const Value(2), fullPath: '阳台/储物柜', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '晾衣区', icon: const Value('👕'), parentId: const Value(6), level: const Value(2), fullPath: '阳台/晾衣区', sortOrder: const Value(2)),
          
          LocationsCompanion.insert(name: '上层', parentId: const Value(36), level: const Value(3), fullPath: '阳台/储物柜/上层', sortOrder: const Value(1)),
          LocationsCompanion.insert(name: '下层', parentId: const Value(36), level: const Value(3), fullPath: '阳台/储物柜/下层', sortOrder: const Value(2)),
        ]);
      });
    }
  }
}