import 'package:flutter_test/flutter_test.dart';
import 'package:home_stock/core/utils/shopping_stock_helper.dart';
import 'package:home_stock/data/database/app_database.dart';

void main() {
  final now = DateTime(2026, 7, 4);

  ShoppingListData listItem({
    int id = 1,
    String name = '牛奶',
    int? relatedItemId,
    double quantity = 1,
  }) {
    return ShoppingListData(
      id: id,
      name: name,
      relatedItemId: relatedItemId,
      quantity: quantity,
      unit: '瓶',
      estimatedPrice: null,
      isPurchased: false,
      isAutoGenerated: false,
      createdAt: now,
    );
  }

  Item mockItem({
    int id = 10,
    String name = '牛奶',
    double currentQuantity = 2,
    String unit = '瓶',
    int status = 0,
  }) {
    return Item(
      id: id,
      name: name,
      categoryId: 1,
      purchaseQuantity: 1,
      packageQuantity: 1,
      currentQuantity: currentQuantity,
      unit: unit,
      safetyStock: 1,
      expiryAlertDays: 3,
      stockAlert: true,
      status: status,
      createdAt: now,
      updatedAt: now,
    );
  }

  group('resolveShoppingStock', () {
    test('relatedItemId 优先匹配', () {
      final snap = resolveShoppingStock(
        shoppingItem: listItem(relatedItemId: 10, quantity: 1),
        activeItems: [mockItem(id: 10, currentQuantity: 3)],
        relatedItem: mockItem(id: 10, currentQuantity: 3),
      );
      expect(snap.displayLabel(), '现有 3 瓶');
      expect(snap.isPossiblyRedundant, isTrue);
    });

    test('名称精确匹配合并数量', () {
      final snap = resolveShoppingStock(
        shoppingItem: listItem(name: '牛奶'),
        activeItems: [
          mockItem(id: 1, currentQuantity: 1),
          mockItem(id: 2, name: '牛奶', currentQuantity: 2),
        ],
      );
      expect(snap.displayLabel(), '现有 3 瓶');
      expect(snap.matchedItemCount, 2);
    });

    test('无匹配显示家里暂无', () {
      final snap = resolveShoppingStock(
        shoppingItem: listItem(name: '酱油'),
        activeItems: [mockItem(name: '牛奶')],
      );
      expect(snap.displayLabel(), '家里暂无');
      expect(snap.hasMatch, isFalse);
    });

    test('库存为 0 仍算有匹配', () {
      final snap = resolveShoppingStock(
        shoppingItem: listItem(relatedItemId: 10),
        activeItems: [mockItem(currentQuantity: 0)],
        relatedItem: mockItem(currentQuantity: 0),
      );
      expect(snap.displayLabel(), '家里暂无');
      expect(snap.hasMatch, isTrue);
    });

    test('现有量小于计划购买量时不提示重复', () {
      final snap = resolveShoppingStock(
        shoppingItem: listItem(relatedItemId: 10, quantity: 3),
        activeItems: [mockItem(currentQuantity: 1)],
        relatedItem: mockItem(currentQuantity: 1),
      );
      expect(snap.isPossiblyRedundant, isFalse);
      expect(snap.hintLabel(), isNull);
    });
  });
}
