version: '3.8'

services:
  backup:
    image: postgres:15
    container_name: homestock_backup
    env_file:
      - .env
    volumes:
      - ./scripts/backup.sh:/backup.sh:ro
      - backups_data:/backups
    depends_on:
      db:
        condition: service_healthy
    command: ["/bin/sh", "/backup.sh"]
    profiles: ["backup"]

  db:
    image: postgres:15
    container_name: homestock_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homestock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  backups_data:
