# Generated by Django 4.2.7 on 2026-03-28 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="图标"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="users.family",
                        verbose_name="所属家庭",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "categories",
                "ordering": ["name"],
                "unique_together": {("name", "family")},
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="位置名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="位置描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="users.family",
                        verbose_name="所属家庭",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="items.location",
                        verbose_name="父位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "位置",
                "verbose_name_plural": "位置",
                "db_table": "locations",
                "ordering": ["name"],
                "unique_together": {("name", "family")},
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="物品名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="物品描述"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "unit",
                    models.CharField(default="个", max_length=20, verbose_name="单位"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="购买日期"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="items/", verbose_name="图片"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="条形码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="items.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.family",
                        verbose_name="所属家庭",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="items.location",
                        verbose_name="位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "物品",
                "verbose_name_plural": "物品",
                "db_table": "items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "category"], name="items_family__ea831e_idx"
                    ),
                    models.Index(
                        fields=["family", "location"], name="items_family__7b2e97_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="items_expiry__6ce21e_idx"
                    ),
                    models.Index(fields=["name"], name="items_name_dd4454_idx"),
                ],
            },
        ),
    ]
