# Generated by Django 4.2.7 on 2026-04-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemUsageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "添加"),
                            ("use", "使用"),
                            ("adjust", "调整"),
                            ("delete", "删除"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("previous_quantity", models.IntegerField(verbose_name="操作前数量")),
                ("current_quantity", models.IntegerField(verbose_name="操作后数量")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="操作描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_history",
                        to="items.item",
                        verbose_name="物品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_usage_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物品使用历史",
                "verbose_name_plural": "物品使用历史",
                "db_table": "item_usage_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
