# Generated by Django 4.2.7 on 2026-03-28 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("full", "全量同步"), ("incremental", "增量同步")],
                        default="incremental",
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_sync_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次同步时间"
                    ),
                ),
                (
                    "current_sync_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="当前同步时间"
                    ),
                ),
                (
                    "items_count",
                    models.IntegerField(default=0, verbose_name="同步物品数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="users.family",
                        verbose_name="家庭",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步记录",
                "verbose_name_plural": "同步记录",
                "db_table": "sync_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("update", "更新冲突"),
                            ("delete", "删除冲突"),
                            ("version", "版本冲突"),
                        ],
                        max_length=20,
                        verbose_name="冲突类型",
                    ),
                ),
                ("server_data", models.JSONField(verbose_name="服务器数据")),
                ("client_data", models.JSONField(verbose_name="客户端数据")),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("server", "以服务器为准"),
                            ("client", "以客户端为准"),
                            ("manual", "手动处理"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="解决方案",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="已解决"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to="items.item",
                        verbose_name="物品",
                    ),
                ),
                (
                    "sync_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="sync.syncrecord",
                        verbose_name="同步记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步冲突",
                "verbose_name_plural": "同步冲突",
                "db_table": "sync_conflicts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(
                fields=["user", "family", "created_at"],
                name="sync_record_user_id_5e5a86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(fields=["status"], name="sync_record_status_01156e_idx"),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["sync_record", "item"], name="sync_confli_sync_re_c23e19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["is_resolved"], name="sync_confli_is_reso_63d4c0_idx"
            ),
        ),
    ]
