import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/database/app_database.dart';
import 'database_provider.dart';

// 购物清单项 Provider
final shoppingListProvider = FutureProvider<List<ShoppingListData>>((ref) async {
  final db = ref.watch(databaseProvider);
  return db.getShoppingList();
});

// 待购清单 Provider（未购买）
final pendingShoppingItemsProvider = FutureProvider<List<ShoppingListData>>((ref) async {
  final db = ref.watch(databaseProvider);
  final items = await db.getShoppingList();
  return items.where((item) => !item.isPurchased).toList();
});

// 已购清单 Provider
final purchasedShoppingItemsProvider = FutureProvider<List<ShoppingListData>>((ref) async {
  final db = ref.watch(databaseProvider);
  final items = await db.getShoppingList();
  return items.where((item) => item.isPurchased).toList();
});

// 系统推荐 Provider（自动生成且未购买）
final autoGeneratedItemsProvider = FutureProvider<List<ShoppingListData>>((ref) async {
  final db = ref.watch(databaseProvider);
  final items = await db.getShoppingList();
  return items.where((item) => item.isAutoGenerated && !item.isPurchased).toList();
});

// 手动添加 Provider（非自动生成且未购买）
final manualItemsProvider = FutureProvider<List<ShoppingListData>>((ref) async {
  final db = ref.watch(databaseProvider);
  final items = await db.getShoppingList();
  return items.where((item) => !item.isAutoGenerated && !item.isPurchased).toList();
});

// 待购数量 Provider
final pendingCountProvider = FutureProvider<int>((ref) async {
  final pendingItems = await ref.watch(pendingShoppingItemsProvider.future);
  return pendingItems.length;
});

// 预估总消费 Provider
final estimatedTotalProvider = FutureProvider<double>((ref) async {
  final pendingItems = await ref.watch(pendingShoppingItemsProvider.future);
  double total = 0;
  for (final item in pendingItems) {
    final price = item.estimatedPrice;
    if (price != null) {
      total += price * item.quantity;
    }
  }
  return total;
});

// 添加购物项
Future<int> addShoppingItem({
  required AppDatabase db,
  required String name,
  double quantity = 1,
  String unit = '件',
  double? estimatedPrice,
  int? relatedItemId,
  bool isAutoGenerated = false,
}) async {
  return db.insertShoppingListItem(
    ShoppingListCompanion.insert(
      name: name,
      quantity: Value(quantity),
      unit: Value(unit),
      estimatedPrice: Value(estimatedPrice),
      relatedItemId: Value(relatedItemId),
      isAutoGenerated: Value(isAutoGenerated),
    ),
  );
}

// 标记为已购买
Future<void> markAsPurchased(AppDatabase db, int id) async {
  final items = await db.getShoppingList();
  final item = items.firstWhere((i) => i.id == id);
  // 创建新记录
  await db.insertShoppingListItem(
    ShoppingListCompanion.insert(
      name: item.name,
      quantity: Value(item.quantity),
      unit: Value(item.unit),
      estimatedPrice: Value(item.estimatedPrice),
      relatedItemId: Value(item.relatedItemId),
      isAutoGenerated: Value(item.isAutoGenerated),
      isPurchased: const Value(true),
    ),
  );
  // 删除旧记录
  await (db.delete(db.shoppingList)..where((s) => s.id.equals(id))).go();
}

// 删除购物项
Future<void> deleteShoppingItem(AppDatabase db, int id) async {
  await (db.delete(db.shoppingList)..where((s) => s.id.equals(id))).go();
}

// 标记全部已购买
Future<void> markAllAsPurchased(AppDatabase db) async {
  final items = await db.getShoppingList();
  final pendingItems = items.where((i) => !i.isPurchased).toList();

  for (final item in pendingItems) {
    await markAsPurchased(db, item.id);
  }
}
