# Generated by Django 4.2.7 on 2026-03-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "库存不足"),
                            ("expired", "已过期"),
                            ("expiring_soon", "即将过期"),
                        ],
                        max_length=20,
                        verbose_name="预警类型",
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(blank=True, null=True, verbose_name="阈值"),
                ),
                ("message", models.TextField(verbose_name="预警信息")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="已解决"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "verbose_name_plural": "库存预警",
                "db_table": "inventory_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "添加"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("consume", "消耗"),
                            ("restock", "补货"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("quantity_before", models.IntegerField(verbose_name="操作前数量")),
                ("quantity_after", models.IntegerField(verbose_name="操作后数量")),
                ("quantity_change", models.IntegerField(verbose_name="数量变化")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存日志",
                "verbose_name_plural": "库存日志",
                "db_table": "inventory_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
