# Generated by Django 4.2.7 on 2026-03-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="items.item",
                verbose_name="物品",
            ),
        ),
        migrations.AddField(
            model_name="inventoryalert",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="items.item",
                verbose_name="物品",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["item", "created_at"], name="inventory_l_item_id_581fbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(
                fields=["item", "alert_type"], name="inventory_a_item_id_e4214b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(
                fields=["is_resolved"], name="inventory_a_is_reso_5c217b_idx"
            ),
        ),
    ]
