import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../core/constants/app_colors.dart';
import '../../core/providers/database_provider.dart';
import '../../core/providers/shopping_provider.dart';
import '../common/widgets/app_empty_state.dart';
import 'widgets/shopping_item_card.dart';
import 'widgets/add_shopping_dialog.dart';

class ShoppingListPage extends ConsumerStatefulWidget {
  const ShoppingListPage({super.key});

  @override
  ConsumerState<ShoppingListPage> createState() => _ShoppingListPageState();
}

class _ShoppingListPageState extends ConsumerState<ShoppingListPage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _shareList(List<dynamic> items) async {
    if (items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('清单为空，无法分享')),
      );
      return;
    }

    final buffer = StringBuffer();
    buffer.writeln('📋 购物清单 (${DateFormat('yyyy-MM-dd').format(DateTime.now())})\n');

    for (final item in items) {
      buffer.writeln('- ${item.name} ${item.quantity} ${item.unit}');
      if (item.estimatedPrice != null) {
        buffer.writeln('  ¥${item.estimatedPrice!.toStringAsFixed(2)}');
      }
    }

    await Share.share(buffer.toString());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.card,
        title: const Text('购物清单'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: () async {
              final pendingItems = await ref.read(pendingShoppingItemsProvider.future);
              await _shareList(pendingItems);
            },
          ),
        ],
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(text: '待购'),
            Tab(text: '已购'),
            Tab(text: '历史'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildPendingTab(),
          _buildPurchasedTab(),
          _buildHistoryTab(),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          AddShoppingDialog.show(
            context,
            onConfirm: (name, quantity, unit, price) async {
              final db = ref.read(databaseProvider);
              await addShoppingItem(
                db: db,
                name: name,
                quantity: quantity,
                unit: unit,
                estimatedPrice: price,
              );
              ref.invalidate(pendingShoppingItemsProvider);
              ref.invalidate(shoppingListProvider);
            },
          );
        },
        child: const Icon(Icons.add),
      ),
    );
  }

  Widget _buildPendingTab() {
    final autoAsync = ref.watch(autoGeneratedItemsProvider);
    final manualAsync = ref.watch(manualItemsProvider);
    final totalAsync = ref.watch(estimatedTotalProvider);

    return RefreshIndicator(
      onRefresh: () async {
        ref.invalidate(autoGeneratedItemsProvider);
        ref.invalidate(manualItemsProvider);
        ref.invalidate(estimatedTotalProvider);
      },
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // 系统推荐区域
          autoAsync.when(
            data: (items) {
              if (items.isEmpty) return const SizedBox.shrink();
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Text('🤖', style: TextStyle(fontSize: 18)),
                      const SizedBox(width: 8),
                      Text(
                        '系统推荐',
                        style: Theme.of(context).textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w600,
                            ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  ...items.map((item) => Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: ShoppingItemCard(
                          name: item.name,
                          quantity: item.quantity,
                          unit: item.unit,
                          estimatedPrice: item.estimatedPrice,
                          isAutoGenerated: true,
                          reason: '库存不足',
                          onCheckChanged: () async {
                            final db = ref.read(databaseProvider);
                            await markAsPurchased(db, item.id);
                            ref.invalidate(autoGeneratedItemsProvider);
                            ref.invalidate(manualItemsProvider);
                            ref.invalidate(shoppingListProvider);
                          },
                          onDelete: () async {
                            final db = ref.read(databaseProvider);
                            await deleteShoppingItem(db, item.id);
                            ref.invalidate(autoGeneratedItemsProvider);
                          },
                        ),
                      )),
                  const SizedBox(height: 16),
                ],
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, stack) => Text('Error: $error'),
          ),

          // 手动添加区域
          manualAsync.when(
            data: (items) {
              if (items.isEmpty && autoAsync.value?.isEmpty == true) {
                return const AppEmptyState(
                  icon: '🛒',
                  title: '购物清单为空',
                  subtitle: '物品用完或库存不足时会自动推荐',
                );
              }
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Text('📝', style: TextStyle(fontSize: 18)),
                      const SizedBox(width: 8),
                      Text(
                        '手动添加',
                        style: Theme.of(context).textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w600,
                            ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  ...items.map((item) => Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: ShoppingItemCard(
                          name: item.name,
                          quantity: item.quantity,
                          unit: item.unit,
                          estimatedPrice: item.estimatedPrice,
                          onCheckChanged: () async {
                            final db = ref.read(databaseProvider);
                            await markAsPurchased(db, item.id);
                            ref.invalidate(autoGeneratedItemsProvider);
                            ref.invalidate(manualItemsProvider);
                            ref.invalidate(shoppingListProvider);
                          },
                          onDelete: () async {
                            final db = ref.read(databaseProvider);
                            await deleteShoppingItem(db, item.id);
                            ref.invalidate(manualItemsProvider);
                          },
                        ),
                      )),
                ],
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, stack) => Text('Error: $error'),
          ),

          const SizedBox(height: 80), // FAB space
        ],
      ),
    );
  }

  Widget _buildPurchasedTab() {
    final purchasedAsync = ref.watch(purchasedShoppingItemsProvider);

    return purchasedAsync.when(
      data: (items) {
        if (items.isEmpty) {
          return const AppEmptyState(
            icon: '✅',
            title: '暂无已购项',
            subtitle: '标记为已购买的物品会显示在这里',
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: items.length,
          itemBuilder: (context, index) {
            final item = items[index];
            return Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: ShoppingItemCard(
                name: item.name,
                quantity: item.quantity,
                unit: item.unit,
                estimatedPrice: item.estimatedPrice,
                isChecked: true,
                onDelete: () async {
                  final db = ref.read(databaseProvider);
                  await deleteShoppingItem(db, item.id);
                  ref.invalidate(purchasedShoppingItemsProvider);
                },
              ),
            );
          },
        );
      },
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stack) => Center(child: Text('Error: $error')),
    );
  }

  Widget _buildHistoryTab() {
    // 历史记录显示所有已删除的（这里暂时显示已购）
    return _buildPurchasedTab();
  }
}
