import 'package:flutter/foundation.dart' show debugPrint;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_radius.dart';
import '../../core/providers/database_provider.dart';
import '../../core/providers/shopping_provider.dart';
import '../../core/providers/shopping_stock_provider.dart';
import '../../core/providers/space_skin_provider.dart';
import '../../core/utils/shopping_stock_helper.dart';
import '../common/widgets/app_empty_state.dart';
import '../common/widgets/app_fab.dart';
import '../common/widgets/app_list_entrance.dart';
import '../common/widgets/warm_scaffold.dart';
import '../common/widgets/app_tab_bar.dart';
import 'widgets/shopping_item_card.dart';
import 'widgets/add_shopping_dialog.dart';

class ShoppingListPage extends ConsumerStatefulWidget {
  const ShoppingListPage({super.key});

  @override
  ConsumerState<ShoppingListPage> createState() => _ShoppingListPageState();
}

class _ShoppingListPageState extends ConsumerState<ShoppingListPage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _shareList(
    List<dynamic> items,
    Map<int, ShoppingStockSnapshot> stockMap,
  ) async {
    final skin = ref.read(spaceSkinProvider);
    if (items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('清单为空，无法分享')),
      );
      return;
    }

    final buffer = StringBuffer();
    buffer.writeln(
      skin.shoppingListShareHeader(DateFormat('yyyy-MM-dd').format(DateTime.now())),
    );
    buffer.writeln();

    for (final item in items) {
      buffer.writeln('- ${item.name} ${item.quantity} ${item.unit}');
      final stock = stockMap[item.id];
      if (stock != null) {
        buffer.writeln('  ${stock.displayLabel(skin: skin)}');
      }
      if (item.estimatedPrice != null) {
        buffer.writeln('  ¥${item.estimatedPrice!.toStringAsFixed(2)}');
      }
    }

    await Share.share(buffer.toString());
  }

  void _invalidateShopping() {
    ref.invalidate(autoGeneratedItemsProvider);
    ref.invalidate(manualItemsProvider);
    ref.invalidate(shoppingListProvider);
    ref.invalidate(pendingShoppingItemsProvider);
    ref.invalidate(pendingShoppingStockProvider);
    ref.invalidate(shoppingRedundantCountProvider);
    ref.invalidate(estimatedTotalProvider);
  }

  /// M4：从库存快照提取卡片展示字段
  ({String? stockLabel, bool redundant, String? hint}) _stockProps(
    int listId,
    AsyncValue<Map<int, ShoppingStockSnapshot>> stockAsync,
  ) {
    final skin = ref.read(spaceSkinProvider);
    return stockAsync.maybeWhen(
      data: (map) {
        final snap = map[listId];
        if (snap == null) return (stockLabel: null, redundant: false, hint: null);
        return (
          stockLabel: snap.displayLabel(skin: skin),
          redundant: snap.isPossiblyRedundant,
          hint: snap.hintLabel(skin: skin),
        );
      },
      orElse: () => (stockLabel: null, redundant: false, hint: null),
    );
  }

  @override
  Widget build(BuildContext context) {
    final skin = ref.watch(spaceSkinProvider);
    return WarmScaffold(
      title: skin.shoppingListLabel,
      actions: [
        IconButton(
          icon: const Icon(Icons.share_outlined),
          tooltip: '分享清单',
          onPressed: () async {
            final pendingItems = await ref.read(pendingShoppingItemsProvider.future);
            final stockMap = await ref.read(pendingShoppingStockProvider.future);
            await _shareList(pendingItems, stockMap);
          },
        ),
      ],
      bottom: AppTabBar(
        controller: _tabController,
        tabs: const [
          AppTabItem(label: '待购', emoji: '📝'),
          AppTabItem(label: '已购', emoji: '✅'),
          AppTabItem(label: '历史', emoji: '📜'),
        ],
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildPendingTab(),
          _buildPurchasedTab(),
          _buildHistoryTab(),
        ],
      ),
      floatingActionButton: AppFloatingActionButton(
        onPressed: () {
          AddShoppingDialog.show(
            context,
            onConfirm: (name, quantity, unit, price) async {
              final db = ref.read(databaseProvider);
              await addShoppingItem(
                db: db,
                name: name,
                quantity: quantity,
                unit: unit,
                estimatedPrice: price,
              );
              ref.invalidate(pendingShoppingItemsProvider);
              _invalidateShopping();
            },
          );
        },
        child: const Icon(Icons.add),
      ),
    );
  }

  Widget _buildStockHintBanner(int redundantCount) {
    if (redundantCount <= 0) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Material(
        color: AppColors.warningLight,
        borderRadius: BorderRadius.circular(AppRadius.md),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          child: Row(
            children: [
              Icon(Icons.info_outline, size: 18, color: AppColors.warning),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  '有 $redundantCount 项家里还有货，采购前看一眼',
                  style: TextStyle(
                    fontSize: 13,
                    color: AppColors.warning,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildPendingTab() {
    final skin = ref.watch(spaceSkinProvider);
    final autoAsync = ref.watch(autoGeneratedItemsProvider);
    final manualAsync = ref.watch(manualItemsProvider);
    final stockAsync = ref.watch(pendingShoppingStockProvider);
    final redundantAsync = ref.watch(shoppingRedundantCountProvider);

    return RefreshIndicator(
      onRefresh: () async {
        _invalidateShopping();
      },
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          redundantAsync.when(
            data: (count) => _buildStockHintBanner(count),
            loading: () => const SizedBox.shrink(),
            error: (_, __) => const SizedBox.shrink(),
          ),
          // 系统推荐区域
          autoAsync.when(
            data: (items) {
              if (items.isEmpty) return const SizedBox.shrink();
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Text('🤖', style: TextStyle(fontSize: 18)),
                      const SizedBox(width: 8),
                      Text(
                        '系统推荐',
                        style: Theme.of(context).textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w600,
                            ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  ...items.asMap().entries.map((entry) {
                    final index = entry.key;
                    final item = entry.value;
                    final stock = _stockProps(item.id, stockAsync);
                    return AppListEntrance(
                      index: index,
                      child: Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: ShoppingItemCard(
                          name: item.name,
                          quantity: item.quantity,
                          unit: item.unit,
                          estimatedPrice: item.estimatedPrice,
                          isAutoGenerated: true,
                          reason: '库存不足',
                          stockLabel: stock.stockLabel,
                          stockPossiblyRedundant: stock.redundant,
                          stockHint: stock.hint,
                          cartoonIndex: index,
                          onCheckChanged: () async {
                            final db = ref.read(databaseProvider);
                            await markAsPurchased(db, item.id);
                            _invalidateShopping();
                          },
                          onDelete: () async {
                            final db = ref.read(databaseProvider);
                            await deleteShoppingItem(db, item.id);
                            _invalidateShopping();
                          },
                        ),
                      ),
                    );
                  }),
                  const SizedBox(height: 16),
                ],
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, stack) => Text('Error: $error'),
          ),

          // 手动添加区域
          manualAsync.when(
            data: (items) {
              if (items.isEmpty && autoAsync.value?.isEmpty == true) {
                return AppEmptyState(
                  icon: '🛒',
                  title: '${skin.shoppingListLabel}为空',
                  subtitle: '物品用完或库存不足时会自动推荐',
                );
              }
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Text('📝', style: TextStyle(fontSize: 18)),
                      const SizedBox(width: 8),
                      Text(
                        '手动添加',
                        style: Theme.of(context).textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w600,
                            ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  ...items.asMap().entries.map((entry) {
                    final autoCount = autoAsync.value?.length ?? 0;
                    final index = autoCount + entry.key;
                    final item = entry.value;
                    final stock = _stockProps(item.id, stockAsync);
                    return AppListEntrance(
                      index: index,
                      child: Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: ShoppingItemCard(
                          name: item.name,
                          quantity: item.quantity,
                          unit: item.unit,
                          estimatedPrice: item.estimatedPrice,
                          stockLabel: stock.stockLabel,
                          stockPossiblyRedundant: stock.redundant,
                          stockHint: stock.hint,
                          cartoonIndex: index,
                          onCheckChanged: () async {
                            final db = ref.read(databaseProvider);
                            await markAsPurchased(db, item.id);
                            _invalidateShopping();
                          },
                          onDelete: () async {
                            final db = ref.read(databaseProvider);
                            await deleteShoppingItem(db, item.id);
                            _invalidateShopping();
                          },
                        ),
                      ),
                    );
                  }),
                ],
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, stack) => Text('Error: $error'),
          ),

          const SizedBox(height: 80), // FAB space
        ],
      ),
    );
  }

  Widget _buildPurchasedTab() {
    final purchasedAsync = ref.watch(purchasedShoppingItemsProvider);

    return purchasedAsync.when(
      data: (items) {
        if (items.isEmpty) {
          return const AppEmptyState(
            icon: '✅',
            title: '暂无已购项',
            subtitle: '标记为已购买的物品会显示在这里',
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: items.length,
          itemBuilder: (context, index) {
            final item = items[index];
            return AppListEntrance(
              index: index,
              child: Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: ShoppingItemCard(
                  name: item.name,
                  quantity: item.quantity,
                  unit: item.unit,
                  estimatedPrice: item.estimatedPrice,
                  isChecked: true,
                  cartoonIndex: index,
                  onDelete: () async {
                    final db = ref.read(databaseProvider);
                    await deleteShoppingItem(db, item.id);
                    ref.invalidate(purchasedShoppingItemsProvider);
                  },
                ),
              ),
            );
          },
        );
      },
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stack) => Center(child: Text('Error: $error')),
    );
  }

  Widget _buildHistoryTab() {
    // 历史记录显示所有已删除的（这里暂时显示已购）
    return _buildPurchasedTab();
  }
}
